### ISSUE TITLE
Pixel represented focal length or real world scale focal length(mm)

### ISSUE THREAD

**Issue by choillee82** [YvanYin/Metric3D#100]
Which kind of focal length do you use in your experiment? Pixel represented focal length or real world scale focal length(mm)?
Datasets you used to train model, they seems support different of focal length depend on datasets.
For example, taskonomy dataset only provide fov information, so to convert it to camera parameter, focal length should be pixel represented value.
But, As far as i know, Nyuv2 and kitti they provide focal length in real world scale(mm).

My question is

Which kind of focal length do you use to align data(canonical transform) with same focal space? pixel or real ?
How to convert real to pixel or pixel to real?

**Comment by choillee82** [comment]
If you use pixel represented focal length, did you use below codes(taskonomy, omnidata) to convert from fov to pixel represented focal length?

**codes in taskonomy**
def get_K(resolution, fov):
    resolution, _ = resolution
    focal_length = 1. / ( 2 * math.tan( fov / 2. ) ) 
    focal_length *= resolution
    offset = resolution /2.
    K = np.array(
        ((   focal_length,    0, offset),
        (    0  ,  focal_length, offset),
        (    0  ,  0,      1       )), dtype=np.float64)
 #   K[:,1] = -K[:,1]
#    K[:,2] = -K[:,2]
    return K

**code in omnidata**
    def _get_cam_to_world_R_T_K(self, point_info: Dict[str, Any], building: str, point: int, view: int, device='cpu') -> List[torch.Tensor]:
        EULER_X_OFFSET_RADS = math.radians(90.0)
        location = point_info['camera_location']
        rotation = point_info['camera_rotation_final']
        fov      = point_info['field_of_view_rads']

        
        # Recover cam -> world
        ex, ey, ez = rotation
        R     = euler_angles_to_matrix(torch.tensor(
                  [(ex - EULER_X_OFFSET_RADS, -ey, -ez)],
                  dtype=torch.double, device=device), 'XZY')
        Tx, Ty, Tz = location
        T     = torch.tensor([[-Tx, Tz, Ty]], dtype=torch.double, device=device) 



        # P3D expects world -> cam
        R_inv = R.transpose(1,2)
        T_inv = -R.bmm(T.unsqueeze(-1)).squeeze(-1)
        # T_inv = -R.bmm(T.unsqueeze(-1)).squeeze(-1)
        # T_inv = T
        # R_inv = R 
        K = FoVPerspectiveCameras(device=device, R=R_inv, T=T_inv, fov=fov, degrees=False).compute_projection_matrix(znear=0.001, zfar=512.0, fov=fov, aspect_ratio=1.0, degrees=False)
        
        return dict(
          cam_to_world_R=R_inv.squeeze(0).float(),
          cam_to_world_T=T_inv.squeeze(0).float(),
          proj_K=K.squeeze(0).float(),
          proj_K_inv=K[:,:3,:3].inverse().squeeze(0).float())

**Comment by choillee82** [comment]
Another question is which kind of depth did you use with taskonomy? zbuffer or euclidean depth?

**Comment by ZachL1** [comment]
1. We use focal lengths in pixels. Focal lengths in millimeters can be converted to pixels by using pixel size(mm), and you can also calculate pixel size(mm) by using sensor size(mm) and imaging resolution.
2. If you only know fov, then yes, you can calculate the focal length in pixels, as you mentioned:
    ```
    def get_K(resolution, fov):
      resolution, _ = resolution
      focal_length = 1. / ( 2 * math.tan( fov / 2. ) ) 
      focal_length *= resolution
      offset = resolution /2.
      K = np.array(
          ((   focal_length,    0, offset),
          (    0  ,  focal_length, offset),
          (    0  ,  0,      1       )), dtype=np.float64)
    
      return K
    ```
    However, please note that omnidata uses the projection matrix of the OpenGL paradigm. K here has different meanings. `K[0,0], K[1,1]` should not correspond to `fx, fy` in pixel units.

3. In all datasets, we use zbuffer depth.

**Comment by choillee82** [comment]
I really appreciate your reply.

**Comment by choillee82** [comment]
I really appreciate your reply.
