### ISSUE TITLE
ConvNext-based backbone missed in training folders?  

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [YvanYin/Metric3D#104]

**Comment by ZachL1** [comment]
In the training folder, we released the training code of Metric3Dv2, so it only contains the ViT backbone.

If you want to train Metric3Dv1 on ConvNeXt, maybe you can refer to the config here: https://github.com/YvanYin/Metric3D/tree/main/mono/configs/_base_/models
Just modify the [import](https://github.com/YvanYin/Metric3D/blob/main/training/mono/configs/RAFTDecoder/vit.raft5.giant2.kitti.py#L2) and [crop_size](https://github.com/YvanYin/Metric3D/blob/main/training/mono/configs/RAFTDecoder/vit.raft5.giant2.kitti.py#L46) in the training config should be fine.
