### ISSUE TITLE
Some questions on fine-tuning

### ISSUE THREAD

**Issue by BaderTim** [YvanYin/Metric3D#105]
Hi there, 
first of all - amazing work! I did some testing with inference and the results were shokingly good.

Now, for my use case, i would like to fine tune the model on my own data. I have a dataset containing images, sparse depth maps and camera intrinsics. **But for now, I would like to try to fine-tune it on kitti first (like you did in the paper), but without normals**

I think there are also some open related issues #91, #98,  but those did not really make it clearer for me.

When I understand correctly according to [this readme](https://github.com/YvanYin/Metric3D/blob/main/training/README.md), first I need to download the checkpoints from [here](https://github.com/YvanYin/Metric3D/blob/main/training/data_server_info/pretrained_weight.py) (what is db_root?).

Then I need to prepare a train, val and test JSON (do I even need 'test'?) [with this code](https://github.com/YvanYin/Metric3D/blob/main/data/gene_annos_kitti_demo.py) which describes the KITTI dataset [similar to this](https://github.com/YvanYin/Metric3D/blob/main/training/data_server_info/annos_test_normal_nyu_example.json) first:
```
{
"files":  [
      {
           "rgb": "kitti/.../.../0000.png", 
           "depth": "kitti/.../.../0000_d.png", 
           "cam_in": [518.8579, 519.4691, 325.58245, 253.73617]
      },
      ...
  ]
}
```

Then, according to the readme, I am ready to run the shell command `bash mono/scripts/training_scripts/train.sh` containing:
```bash
cd ../../../

python  mono/tools/train.py \
        mono/configs/RAFTDecoder/vit.raft5.small.sanity_check.py \
        --use-tensorboard \
        --launcher slurm \
        --experiment_name set1
```

So, I think I obviously need to modify the training command. When looking into the args in [training/mono/tools/train.py](https://github.com/YvanYin/Metric3D/blob/main/training/mono/tools/train.py), I find this:

- config: train config file path
- --work-dir: the dir to save logs and models
- --tensorboard-dir: the dir to save tensorboard logs
- --load-from: the checkpoint file to load weights from
- --resume-from: the checkpoint file to resume from
- --no-validate: whether not to evaluate the checkpoint during training
- --gpu-ids: ids of gpus to use (only applicable to non-distributed training)
- --seed: random seed
- --deterministic: whether to set deterministic options for CUDNN backend
- --use-tensorboard: ~~whether to set deterministic options for CUDNN backend~~ I think you mean wether to use tensorboard?
- --options: custom options
- --node_rank: number of nodes
- --nnodes: number of nodes
- --launcher: job launcher
- --local_rank: rank
- --experiment_name: the experiment name for mlflow

Most of this seems clear to me, although not everything. More important is, that I need a config file for training for the `config`-flag. But, how is this config file structured?  
I see that you provided example configs in [training/mono/configs/test_configs_vit_small/kitti.vit.dpt.raft.py](https://github.com/YvanYin/Metric3D/blob/main/training/mono/configs/test_configs_vit_small/kitti.vit.dpt.raft.py), but this title cleary states test config and I do not really unterstand some of its content.

Sooo, this brings me to the following main questions:
1) How does the training config look like? Could you provide an example?
2) What is db_root in the model weights file? You define it as file server path, could you quickly elaborate on this please?
3) Do I need a dataset-json for testing? Or can I just use train and val?
4) What differences would there be to this process if I ever use a custom dataset instead of kitti?
5) Are input stereo depth maps and lidar depth maps projected to the camera position already, or does your pipeline do this?
6) How would a demo shell train.py command look for non-distributed training with a single GPU? (A100)

Thank you a lot!

**Comment by ZachL1** [comment]
1. We provide a number of training config files in `training/mono/configs/RAFTDecoder`. These configs all use RAFTDecoder, but with a different ViT backbone, and different training data.
2. the path of the weights in `pretrained_weight.py`, e.g. `vit_small_reg` is relative to `db_root`.
3. before training (`bash mono/scripts/training_scripts/train.sh`) you only need to prepare the train and val json. before testing (`bash mono/scripts/test_scripts/test_vit.sh`) you need to prepare test json . When you prepare the json you need to be aware that the path to the json file is recorded in `data_server_info/public_datasets.py`, as well as a `db_root` similar to the one just mentioned. That is, `db_root` + `depth_root` + `<depth in json>` should be the absolute path to `depth.png`. normal, meta_data are similar.
4. If you are using a custom dataset, I think the easiest way to do this is to treat it as a kitti. you can do this in three steps:
    1. prepare the json according to your needs and set up the path reasonably well as mentioned in point 3;
    2. modify [metric_scale](https://github.com/YvanYin/Metric3D/blob/main/training/mono/configs/_base_/datasets/kitti.py#L9) and [transform pipeline](https://github.com/YvanYin/Metric3D/blob/main/training/mono/configs/RAFTDecoder/vit.raft5.giant2.kitti.py#L85) in the training config if needed.
    3. rewrite the [process_depth()](https://github.com/YvanYin/Metric3D/blob/main/training/mono/datasets/kitti_dataset.py#L168) method in `kitti_dataset.py`. If needed, `load_norm_label()` should also be rewritten.
5. If the raw data is disparity or point cloud, we will preprocess it when generating the json. In the current training pipeline, the metric gt depth should be read directly for all datasets. If you have questions about a particular dataset, you can check how the inherited classes in `mono/datasets` override the `load_rgb_depth()` and `process_depth()` methods.
6. A single GPU can also do the training. @JUGGHM will share the command.

**Comment by BaderTim** [comment]
> 1. We provide a number of training config files in `training/mono/configs/RAFTDecoder`. These configs all use RAFTDecoder, but with a different ViT backbone, and different training data.
> 2. the path of the weights in `pretrained_weight.py`, e.g. `vit_small_reg` is relative to `db_root`.
> 3. before training (`bash mono/scripts/training_scripts/train.sh`) you only need to prepare the train and val json. before testing (`bash mono/scripts/test_scripts/test_vit.sh`) you need to prepare test json . When you prepare the json you need to be aware that the path to the json file is recorded in `data_server_info/public_datasets.py`, as well as a `db_root` similar to the one just mentioned. That is, `db_root` + `depth_root` + `<depth in json>` should be the absolute path to `depth.png`. normal, meta_data are similar.
> 4. If you are using a custom dataset, I think the easiest way to do this is to treat it as a kitti. you can do this in three steps:
>    
>    1. prepare the json according to your needs and set up the path reasonably well as mentioned in point 3;
>    2. modify [metric_scale](https://github.com/YvanYin/Metric3D/blob/main/training/mono/configs/_base_/datasets/kitti.py#L9) and [transform pipeline](https://github.com/YvanYin/Metric3D/blob/main/training/mono/configs/RAFTDecoder/vit.raft5.giant2.kitti.py#L85) in the training config if needed.
>    3. rewrite the [process_depth()](https://github.com/YvanYin/Metric3D/blob/main/training/mono/datasets/kitti_dataset.py#L168) method in `kitti_dataset.py`. If needed, `load_norm_label()` should also be rewritten.
> 5. If the raw data is disparity or point cloud, we will preprocess it when generating the json. In the current training pipeline, the metric gt depth should be read directly for all datasets. If you have questions about a particular dataset, you can check how the inherited classes in `mono/datasets` override the `load_rgb_depth()` and `process_depth()` methods.
> 6. A single GPU can also do the training. @JUGGHM will share the command.

Thank you very much for your comprehensive answer, I finally got it to work! 

I used the following training command to train on a single gpu (requires ~20GB VRAM with current config):
```bash
python mono/tools/train.py \
        mono/configs/RAFTDecoder/vit.raft5.small.kitti.py \
        --use-tensorboard \
        --experiment_name test1 \
        --load-from checkpoints/metric_depth_vit_small_800k.pth \
        --seed 42 \
        --launcher None 
```
and then implemented a custom training config for the small vision transformer in `training/mono/configs/RAFTDecoder` and modified the kitti.py in `training/mono/configs/_base_/datasets/kitti.py`: [metric3d_custom_config.zip](https://github.com/user-attachments/files/15799696/metric3d_custom_config.zip)

In `training/data_server_info/public_datasets.py` I modified KITTI the following way:
```python
db_info['KITTI'] = {
    'db_root': 'data/mydataset',
    'data_root': '',
    'train_annotations_path': 'train/metric3d.json',
    'test_annotations_path': 'test/metric3d.json',
    'val_annotations_path': 'val/metric3d.json',
}
```

I have the following folder structure (pretrained dino from [here](https://github.com/facebookresearch/dinov2?tab=readme-ov-file#pretrained-model))
```
Metric3D
    training
        checkpoints
            dinov2_vits14_reg4_pretrain.pth
            metric_depth_vit_small_800k.pth
        data
            mydataset
                train  
                    depth/
                    image/
                    metric3d.json
                val
                    depth/
                    image/
                    metric3d.json
                test
                    depth/
                    image/
                    metric3d.json
        data_server_info
        mono
        ....
```




i also had some issues during setup, which I fixed this way

```
conda create -n metric3d python=3.11.9
conda activate metric3d
```
first set the versioning of numpy in the requirements_v2.txt to 1.23.5, then call
```
pip install -r requirements_v2.txt
```
then install
```
pip install h5py mmsegmentation tensorboard
```
then comment out line 61-63 in ``/anaconda/envs/metric3d/lib/python3.11/site-packages/mmseg/__init__.py: ``
```python
# assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
#     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
#     f'Please install mmcv>=2.0.0rc4.'
```

**Comment by ZachL1** [comment]
Well done and thank you for sharing! 

Given that current training pipeline is indeed a bit complex, maybe later we will put together some FAQs and guidance to make everything clearer. This will take some time.

**Comment by BaderTim** [comment]
### I am crashing when using online evaluation with the above setup. To prevent it, I did the following:



setup change to above: install matplotlib version 3.8.4

in `training/mono/configs/RAFTDecoder/vit.raft5.small.kitti.py` change line 59 to online_eval=True

### **and do some bug fixes in code** 

#### `training/mono/utils/do_train.py`
at line 405 call dist.barrier() only when distributed
```python
if cfg.distributed:
    dist.barrier()
```
around line 413 comment out save_point (getting the dataset length only works after creating an iterator, e.g. with enumerate)  
```python
# save_point = max(int(len(val_dataloader) / 5), 1)  
```
and add it before eval results around line 437 before the if instead  
```python
# save evaluation results
save_point = max(int(len(val_dataloader) / 5), 1)
if i%save_point == 0 and main_process():
...
```
#### `training/mono/utils/visualization.py`
uncomment arguments from line 30 and 31
```python
def save_normal_val_imgs(
    iter: int, 
    pred: torch.tensor, 
    targ: torch.tensor,  # this one
    rgb: torch.tensor,  # and this one
    filename: str, 
    save_dir: str, 
    tb_logger=None, 
    mask=None,
    ):
```

**Comment by kishore-greddy** [comment]
@BaderTim Were you successful in finetuning the model on KITTI dataset? If yes, could you please let me know how many iterations did you train the model for, on which GPU(s), and how long the training took to complete? Thanks in advance.

**Comment by BaderTim** [comment]
Hi @kishore-greddy, I did not fine-tune on KITTI but instead just applied the same methodology to my own dataset. I could train the ViT-Giant model on a single A100 GPU - training peaked at around 78GB VRAM

**Comment by leoShen917** [comment]
@BaderTim @ZachL1 Hi, thanks for sharing the finetune process. I'm trying to fine tune the model using the sparse depth of the point cloud, have you done something similar?  Looking forward to your reply!

**Comment by Gear-dev-sudo** [comment]
@BaderTim Hi, I followed your tutorial on finetuning, the training loss seem while well. But when I ran inference on my fine-tuned checkpoint with the config alongside this checkpoint, the model spit out garbage, are you able to run inference on your fine-tuned model?

**Comment by oywenjun11** [comment]
@BaderTim Hi, thank you very much for your willingness to contribute your fine-tuning experience. I am an AI beginner. I have read many comments on the question, and I still don’t quite understand. The depth map in the data set used requires sparse point clouds or converted ones. Depth map (grayscale image), thank you in advance for your answer, thank you

**Comment by Sissi-lu** [comment]
Hi, thank you for sharing. I changed the configuration file to my own dataset as well. And I found that when I tried to run the training process of ViT-Small model on a single A6000 GPU, there were always two GPUs being used. As a result, The training process of Forward function of BaseDepthModel facing RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
Do you encounter such a problem? Thanks in advance!

**Comment by Linengyao** [comment]
> 嗨，感谢您的分享。我也将配置文件更改为我自己的数据集。我发现，当我尝试在单个 A6000 GPU 上运行 ViT-Small 模型的训练过程时，总是使用两个 GPU。因此，BaseDepthModel 的 Forward 函数的训练过程面临 RuntimeError： Expected all tensors to be on the same device， but found least two devices， cuda：0 and cuda：1！你遇到这样的问题吗？提前致谢！

没有，我在单个GPU上跑，并且将其设置为单卡训练，这个代码默认是多卡训练的，但是我训练完出现了梯度为nan和虚数的情况，并且测试训练模型的时候出现模型全部都输出一个数的情况
