### ISSUE TITLE
 Pytorch Hub Normal Surface Estimation

### ISSUE THREAD

**Issue by RoenTh** [YvanYin/Metric3D#106]
Hello, you work is amasing!
I am new in AI and wanted to ask if it is possible to also get the predicted normal surface using the pytorch hub like the pred_depth?

**Comment by ZachL1** [comment]
We have added examples of surface normal estimation, hope it helps.
https://github.com/YvanYin/Metric3D/blob/main/hubconf.py#L213

**Comment by RoenTh** [comment]
Thank you very helpful!
