### ISSUE TITLE
Some questions in the experiment

### ISSUE THREAD

**Issue by xuncpp** [YvanYin/Metric3D#109]
Hello! first of all, thank you for your excellent work！
Next I will talk about some minor problems I encountered in hugging face, which are not serious.
first,in app.py
```
np.save(depth_file, pred_depth) 
np.save(normal_file, pred_depth) 
```
The second pred_depth might be pred_normal
second,in do test.py
I think have done BGR to RGB twice

Then I want to ask a question that really bothers me.
I tested many scenes and found that the effect is not very good when there is a foreground, but part of the sky is behind. I am more interested in the subject in the front, rather than the small part of the sky in the back.
How can I improve it?
My initial idea is to set the part exceeding a certain threshold to zero or empty? I don't know if it works, I haven't experimented yet.
such as:
![123](https://github.com/YvanYin/Metric3D/assets/143597475/a3c555c4-abfa-4046-88d8-924780a77dea)

<img width="833" alt="1234" src="https://github.com/YvanYin/Metric3D/assets/143597475/9c65bac8-2a74-4af2-b43f-e9ea97033d98">

Thanks again to the author for excellent work！

**Comment by ZachL1** [comment]
> first,in app.py
> ```
> np.save(depth_file, pred_depth) 
> np.save(normal_file, pred_depth) 
> ```
> The second pred_depth might be pred_normal

Thank you for pointing out this mistake, we have corrected it on hf.


> second,in do test.py
> I think have done BGR to RGB twice

Where are you referring to and can you describe it more specifically?


> Then I want to ask a question that really bothers me.
> I tested many scenes and found that the effect is not very good when there is a foreground, but part of the sky is behind. I am more interested in the subject in the front, rather than the small part of the sky in the back.
> How can I improve it?
> My initial idea is to set the part exceeding a certain threshold to zero or empty? I don't know if it works, I haven't experimented yet.

I believe the predicted metric depth should be accurate, but the visualization doesn't look very good due to the very large depth values in the sky. You can set the part exceeding a certain threshold to zero before color mapping. The pre-trained Metric3D should predict the sky depth as 200m or 150m as I recall, and in general setting the threshold to 100m should work for most scenes.

**Comment by xuncpp** [comment]
Thank you very much for your answer! It is indeed a visualization problem, which has been solved. 
Regarding the second question.I may not have made it clear. What I meant is In line 73 of app.py,you use img = cv2.cvtColor(cv_image, cv2.COLOR_BGR2RGB) and in transform_test_data_scalecano function in line 75，you use it again.
Thanks again！

**Comment by JUGGHM** [comment]
> Thank you very much for your answer! It is indeed a visualization problem, which has been solved. Regarding the second question.I may not have made it clear. What I meant is In line 73 of app.py,you use img = cv2.cvtColor(cv_image, cv2.COLOR_BGR2RGB) and in transform_test_data_scalecano function in line 75，you use it again. Thanks again！

You could clip the depth range, or mask out the unreliable sky regions using the predicted confidence map / some proxy sky segmentors.

**Comment by JUGGHM** [comment]
Here is the confidence. Use something like (confidence < 0.8) to filter. (https://github.com/YvanYin/Metric3D/blob/6a5830569f8fd8867e1b6a834a7edfe0658077a9/mono/utils/do_test.py#L155)
