### ISSUE TITLE
GRUSequenceLoss quite high, is it normal?

### ISSUE THREAD

**Issue by BaderTim** [YvanYin/Metric3D#111]
When training on the small ViT model, is it normal to have such a high GRUSequenceLoss?

![image](https://github.com/YvanYin/Metric3D/assets/61239494/90ffbb28-cd85-4e11-90a7-2ae56c620246)

**Comment by YvanYin** [comment]
You can train more steps and review the loss curve.

**Comment by JUGGHM** [comment]
It is common because it's the summation of losses from all iterative steps.
