### ISSUE TITLE
请问使用这个模型做深度估计需要先把图像去畸变吗

### ISSUE THREAD

**Issue by xiangyulee** [YvanYin/Metric3D#112]
如果不去畸变会不会很影响预测的结果

**Comment by Owen-Liuyuxuan** [comment]
The result in the 2D visualization is good (sharp edges and clean surface) without rectification.

But if you want to project the result to 3D, you would better do rectification before.

**Comment by xiangyulee** [comment]
> The result in the 2D visualization is good (sharp edges and clean surface) without rectification.
> 
> But if you want to project the result to 3D, you would better do rectification before.

明白了，感谢
