### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by baibizhe** [YvanYin/Metric3D#12]
![image](https://github.com/YvanYin/Metric3D/assets/33809209/551a3709-1347-4455-a0d5-e8843a42e29c)
 bug?

**Comment by YvanYin** [comment]
1. For NYU dataset, you can get fx and fy from the original dataset.
2. You don't need to adjust the depth_normalize, it is set in our training and fixed in training and inference. 
3. Yes.
4. What do you mean about the depth scale?
