### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by P20000911** [YvanYin/Metric3D#120]
I am getting the following error:
<img width="460" alt="error" src="https://github.com/YvanYin/Metric3D/assets/143408306/f9392740-467f-4c3d-b53b-25110946ed9d">

**Comment by ahinchoi** [comment]
Hi!
I have also come across this error, and would be immensely grateful if you could please elaborate upon how you resolved it.
Thank you for your time and consideration in advance!

**Comment by P20000911** [comment]
Sorry I can't find the article that contains the solution, my impression is that I need to download his checkpoint and then modify some code (path, file name, etc.).
