### ISSUE TITLE
Normal.npy and Pointcloud shapes doesn't match.

### ISSUE THREAD

**Issue by HardikJain02** [YvanYin/Metric3D#128]
Are normals intended to match each point in the point cloud? If not, please explain the correlation between normal and pointcloud.

for example,
image shape: 736 * 917 [W * H]
Points shape: (674912, 3)
Normals shape: After transpose- (304304, 3)  Before Transpose: [3, 616, 494]

**Comment by JUGGHM** [comment]
It should be fixed now by this line:
https://github.com/YvanYin/Metric3D/blob/14d33d4b5cb386e1885cba95415442f7f17d853f/mono/utils/do_test.py#L362

**Comment by HardikJain02** [comment]
Thank you so much
