### ISSUE TITLE
Using Mapillary Dataset

### ISSUE THREAD

**Issue by XiangMochu** [YvanYin/Metric3D#13]
Hi there, very inspiring work! I've been telling everyone around me that this is my favourate paper recently, and I personally regard Metric3D as one of the milestones in MDE. 

I have a question about Mapillary Planet-Scale Depth Dataset that is uesd in this paper: what is the scale of the ground truth in Mapillary dataset? When we read depth images and convert them into metric 2D maps, we divide them using a scaling factor like `metric_depth = depth / 512` or something, and provide metric depth supervision. I tried to find this scaling factor for a long time and couldn't get any clue, I wonder how you get the metric depth from the Mapillary dataset?

Looking forward to your reply!
Mochu

**Comment by YvanYin** [comment]
Hi, thank you for your attention to our work.
The Mapillary dataset has a very very coarse metric scale, which is recovered from GPS. You can check it from their website or github. Owing to this, I didn't enforce the metric supervision on the mappilary dataset, i.e. remove the Silog loss on this dataset. But I still use vnl, pwn.... losses on it.

**Comment by XiangMochu** [comment]
Thank you so much!
