### ISSUE TITLE
disparity or depth?

### ISSUE THREAD

**Issue by thucz** [YvanYin/Metric3D#131]
Is the model prediction depth or 1.0 / depth (inverse depth)?

I visualize the depth output. it seems that the far objects have smaller values in the prediction map.
![depth_mono_vis](https://github.com/user-attachments/assets/d9000c39-0651-43a9-8197-e03cb4699228)
![rgb_vis](https://github.com/user-attachments/assets/a4d11824-37a2-44f3-b1bd-85b706a4d4b0)

**Comment by thucz** [comment]
> Hi @thucz did you find the answer for it?

Depth

**Comment by AD-lite24** [comment]
@thucz so do you know how we can scale the outputs to metric depth (ie. in meters). The authors haven't exactly clarified it well

**Comment by thucz** [comment]
I don't know, either. There is no very standard answer to this question.

Aditya Dandwate ***@***.***> 于2024年9月1日周日 21:59写道：

**Comment by Vincent630** [comment]
> @thucz so do you know how we can scale the outputs to metric depth (ie. in meters). The authors haven't exactly clarified it well

Did you konw how to convert this depth to metric depth?
