### ISSUE TITLE
关于规范化相机问题

### ISSUE THREAD

**Issue by puyiwen** [YvanYin/Metric3D#15]
您好，我想知道规范化相机是以RGB相机内参还是深度相机内参做转换？

**Comment by JUGGHM** [comment]
是RGB相机

**Comment by puyiwen** [comment]
> 是RGB相机

不好意思再次打扰您，我没有找到DIML数据和taskonomy数据的RGB相机内参，您方便提供一下这两个数据集的相机内参吗？我的邮箱291931809@qq.com，万分感激！

**Comment by YvanYin** [comment]
DIML和Taskonomy可以从数据集的主页下载到，我们这边当前不太方便传输出去。
