### ISSUE TITLE
Dataset content issues

### ISSUE THREAD

**Issue by oywenjun11** [YvanYin/Metric3D#155]
Hi, thank you for sharing your work, I'm curious to see if the dataset used to fine-tune the model must only use sparse point cloud depth maps, or if it is converted into depth maps, I hope you can answer my common question, thank you

**Comment by YvanYin** [comment]
It needs depth maps for finetuning, no matter sparse or dense. But dense depths could get better performance.

**Comment by oywenjun11** [comment]
> 需要深度图进行微调，无论是稀疏还是密集。但密集深度可以获得更好的性能。

Thank you very much for answering my question, thank you
