### ISSUE TITLE
About the scale of the depth map

### ISSUE THREAD

**Issue by 942411526** [YvanYin/Metric3D#16]
Is the depth map measured in meters? If we use our own images to make predictions, we can provide rough camera parameters

**Comment by JUGGHM** [comment]
> Is the depth map measured in meters? If we use our own images to make predictions, we can provide rough camera parameters

In meters

**Comment by Moeez-Muslim** [comment]
> Is the depth map measured in meters? If we use our own images to make predictions, we can provide rough camera parameters

I'm also trying to estimate the depth in meters, but I'm still unsure how to achieve that using the generated depth map. I'll really appreciate if you can appreciate any leads. 
P.S. I'm using the ViT Giant2 version
