### ISSUE TITLE
Converting Depth Map Pixel Values to Real-World Units (Meters)

### ISSUE THREAD

**Issue by Moeez-Muslim** [YvanYin/Metric3D#169]
Thank you for making this great repository available! I’m using the ViT model, and I’m trying to convert the generated depth map pixel values into real-world units (like meters). I have a specific dataset that I would like to fine-tune the model on, and I’m particularly interested in calculating the distance of some already identified objects in the dataset images.

For reference, I have the ground truth distance of these objects from the camera in meters, and I would like to understand the process of converting the depth values produced by the model to match these real-world distances.

Could you please help clarify:

1. How can I convert the pixel values from the depth map to real distances (e.g., meters)?

2. Is there any scaling factor or specific transformation required to go from pixel values to actual physical units?

3. If not directly possible, could you suggest an approach or workaround to achieve this?

Any pointers or resources would be greatly appreciated! Thanks in advance for your help.

**Comment by JUGGHM** [comment]
Thanks for your questions, I hope these answers help:

1. Suppose we have a canonical depth **D_c** from the network, it has a fixed resolution 616*1064 with fixed focal **f_c** length of **1000** pixels. We need to transform it back to real world by two steps:

- Scaling from resizing:
Let's suppose the original figure is 308*532.  When we resize the output back to the original one (x1/2), the focal should be scale accordingly by **f_1 =1/2 f_c = 500**. For images without the same aspect ratio, we have some crop and padding strategies. In this step, the depth image is resized accordingly.

- Scaling from focal:
We know the real focal **f_real**. According to the pinhole camera projection equation, X/delta_u = Z/focal, the Z-depth should change proportionally with focal, that is: **Z_real = Z_out * f_real / f_1**.

- If we want to get a canonical depth from groundtruth, just inverse the transformation above.

2. The scaling factor is describe above 

3. It is possible.

**Comment by Moeez-Muslim** [comment]
Thank you for clarification. One more thing, does the RGB depth map encodes the depth value like this?

> Depth Value = R×256^2 + G×256 + B
