### ISSUE TITLE
Incorrect scale

### ISSUE THREAD

**Issue by chauncy-hw** [YvanYin/Metric3D#17]
Thank you for your excellent work! We use correct intrinsics, but the scale is wrong. The ground truth (GT) width of the two lines is 3.5m, but the estimated width is 15m~25m. We have tried adjusting the 'crop_size', but we find that it is a sensitive parameter. Different values have a large influence on the results. Can you give me some advice to solve these problems? Thank you.

**Comment by JUGGHM** [comment]
Could you please tell us what's your image size and the corresponding scale drift? We expect a forward resolution that is close to both your original image resolution and the size used for training.

**Comment by chauncy-hw** [comment]
The parameters of our camera are: width: 1920, height: 1080, fx: 1947.99, fy: 1948.421021, cx: 967.802307, cy: 538.507385.
So the "cam_in" parameter of "test_annotations.json" are set as follows: [1947.989014, 1948.421021, 967.802307, 538.507385].
We use "convlarge.0.3_150.py" as default config. When we set "crop_size" as (544, 1216), the predicted distance (target segment) is 15m. We change "crop_size" as (1216,1952), and the predicted distance is 20m. However, the ground truth is about 3.5m.
Apart from the above changes, we have not changed other configurations (we used the default checkpoint, no training). I don't know if there are some errors in my setting, thank you for your help!

**Comment by JUGGHM** [comment]
> The parameters of our camera are: width: 1920, height: 1080, fx: 1947.99, fy: 1948.421021, cx: 967.802307, cy: 538.507385. So the "cam_in" parameter of "test_annotations.json" are set as follows: [1947.989014, 1948.421021, 967.802307, 538.507385]. We use "convlarge.0.3_150.py" as default config. When we set "crop_size" as (544, 1216), the predicted distance (target segment) is 15m. We change "crop_size" as (1216,1952), and the predicted distance is 20m. However, the ground truth is about 3.5m. Apart from the above changes, we have not changed other configurations (we used the default checkpoint, no training). I don't know if there are some errors in my setting, thank you for your help!

So I assume it is a high-resolution camera used indoors, right? Have you tried even smaller resolutions like  (540, 960) which is common for indoor datasets?

**Comment by chauncy-hw** [comment]
> > The parameters of our camera are: width: 1920, height: 1080, fx: 1947.99, fy: 1948.421021, cx: 967.802307, cy: 538.507385. So the "cam_in" parameter of "test_annotations.json" are set as follows: [1947.989014, 1948.421021, 967.802307, 538.507385]. We use "convlarge.0.3_150.py" as default config. When we set "crop_size" as (544, 1216), the predicted distance (target segment) is 15m. We change "crop_size" as (1216,1952), and the predicted distance is 20m. However, the ground truth is about 3.5m. Apart from the above changes, we have not changed other configurations (we used the default checkpoint, no training). I don't know if there are some errors in my setting, thank you for your help!
> 
> So I assume it is a high-resolution camera used indoors, right? Have you tried even smaller resolutions like (540, 960) which is common for indoor datasets?

No, the data comes from the urban driving scenario we collected, and 3.5m is the distance between the two lane lines. We tried downsampling the image to (480, 270) and adjusting intrinsics, but the results were similar to the current situation.

**Comment by JUGGHM** [comment]
> > > The parameters of our camera are: width: 1920, height: 1080, fx: 1947.99, fy: 1948.421021, cx: 967.802307, cy: 538.507385. So the "cam_in" parameter of "test_annotations.json" are set as follows: [1947.989014, 1948.421021, 967.802307, 538.507385]. We use "convlarge.0.3_150.py" as default config. When we set "crop_size" as (544, 1216), the predicted distance (target segment) is 15m. We change "crop_size" as (1216,1952), and the predicted distance is 20m. However, the ground truth is about 3.5m. Apart from the above changes, we have not changed other configurations (we used the default checkpoint, no training). I don't know if there are some errors in my setting, thank you for your help!
> > 
> > 
> > So I assume it is a high-resolution camera used indoors, right? Have you tried even smaller resolutions like (540, 960) which is common for indoor datasets?
> 
> No, the data comes from the urban driving scenario we collected, and 3.5m is the distance between the two lane lines. We tried downsampling the image to (480, 270) and adjusting intrinsics, but the results were similar to the current situation.

This is very strange. We have included a wide range of automotive datasets for training. The scale drift should not be so large. Is it available to provide this particular example?

**Comment by jay25208** [comment]
请问以上问题解决了吗？ @chauncy-hw

**Comment by Ghul-huan** [comment]
请问以上问题解决了吗？ @chauncy-hw
