### ISSUE TITLE
how to remove the time about inference

### ISSUE THREAD

**Issue by 942411526** [YvanYin/Metric3D#18]
Dear author,
I want to predict the depth in our own dataset with your model. There are more than 100 thousand images in the dataset. We want to remove the note of time about prediction such as  00:00, ?it/s ?   I can't find the code to print it

**Comment by JUGGHM** [comment]
> Dear author, I want to predict the depth in our own dataset with your model. There are more than 100 thousand images in the dataset. We want to remove the note of time about prediction such as 00:00, ?it/s ? I can't find the code to print it

Change this [save_interval](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/utils/do_test.py#L232C5-L232C19) to a larger number and the program will not print/save results so frequently.

**Comment by 942411526** [comment]
> > Dear author, I want to predict the depth in our own dataset with your model. There are more than 100 thousand images in the dataset. We want to remove the note of time about prediction such as 00:00, ?it/s ? I can't find the code to print it
> 
> Change this [save_interval](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/utils/do_test.py#L232C5-L232C19) to a larger number and the program will not print/save results so frequently.

I want to let the depth model become a part of our network to support depth maps. but the print such as  00:00, ?it/s  every time so I want to remove it . The "save_interval" may not influent the print, we do not save any depth maps
