### ISSUE TITLE
Single-machine multi-GPU training or inference

### ISSUE THREAD

**Issue by sunpihai-up** [YvanYin/Metric3D#20]
Thank you for contributing such a great job.
I want to use Metric3D for single-machine multi-GPU training or testing, but I found that it is missing some information, such as: `dist_params` in the configuration.
Do you have any suggestions on this?

**Comment by JUGGHM** [comment]
Try to set `cfg.dist_params` with corresponding sub-variables like `{'port': None, 'backend': 'nccl', 'dist_url': 'env://', 'nnodes': 8, 'node_rank': 0, 'num_gpus_per_node': 8, 'world_size': 64}`

**Comment by sunpihai-up** [comment]
> Try to set `cfg.dist_params` with corresponding sub-variables like `{'port': None, 'backend': 'nccl', 'dist_url': 'env://', 'nnodes': 8, 'node_rank': 0, 'num_gpus_per_node': 8, 'world_size': 64}`

Very helpful advice, thank you for your suggestions.
