### ISSUE TITLE
The use of DIML dataset

### ISSUE THREAD

**Issue by LiheYoung** [YvanYin/Metric3D#21]
Hi, thanks for your amazing work! 

I find that you use ~122K training images from the DIML dataset, however, the official raw DIML dataset seems to contain 2M training images in total. Could you please introduce how to obtain these 122K images from DIML? Thank you very much.

**Comment by YvanYin** [comment]
We only used the outdoor part of DIML.

**Comment by LiheYoung** [comment]
Thank you for your quick reply. However, according to the table (from DIML [paper](https://browse.arxiv.org/pdf/2110.11590.pdf)) below, there are 322K outdoor training images in DIML. And are there any reasons for discarding the indoor part of DIML, and only using the synthetic Taskonomy dataset for indoor training? 

<img width="596" alt="截屏2023-10-08 15 28 21" src="https://github.com/YvanYin/Metric3D/assets/47178369/24403fa5-8844-4967-a263-3abb8d8f0ec3">

**Comment by JUGGHM** [comment]
> Thank you for your quick reply. However, according to the table (from DIML [paper](https://browse.arxiv.org/pdf/2110.11590.pdf)) below, there are 322K outdoor training images in DIML. And are there any reasons for discarding the indoor part of DIML, and only using the synthetic Taskonomy dataset for indoor training?
> 
> <img alt="截屏2023-10-08 15 28 21" width="596" src="https://user-images.githubusercontent.com/47178369/273451414-24403fa5-8844-4967-a263-3abb8d8f0ec3.png">

We found some problems when pre-processing the data and did not use it.

**Comment by YvanYin** [comment]
> Thank you for your quick reply. However, according to the table (from DIML [paper](https://browse.arxiv.org/pdf/2110.11590.pdf)) below, there are 322K outdoor training images in DIML. And are there any reasons for discarding the indoor part of DIML, and only using the synthetic Taskonomy dataset for indoor training?
> 
> <img alt="截屏2023-10-08 15 28 21" width="596" src="https://user-images.githubusercontent.com/47178369/273451414-24403fa5-8844-4967-a263-3abb8d8f0ec3.png">

The stereo calibration is broken in provided some data, thus we remove them. You could download them and check it.

**Comment by LiheYoung** [comment]
Thank you for your answer! About the first point, I find that the zip file of some scenes cannot be unzipped. Do you mean this by "broken"?

**Comment by YvanYin** [comment]
Yes, this is a problem. Apart from that, some scenes' stereo images are not well rectified.

**Comment by LiheYoung** [comment]
Thank you a lot!
