### ISSUE TITLE
关于论文3.1章中公式的问题

### ISSUE THREAD

**Issue by myalos** [YvanYin/Metric3D#22]
论文3.1节中， 深度，物体面积，物体成像面积，以及焦距之间的几何关系，为什么是\hat{S}比上\hat{S}^\prime，而不是\hat{S}比上\hat{S}^\prime外面再加个根号啊。假设物体是一个圆，投影也是一个圆，假设深度是焦距的2倍，那么圆的面积应该是投影面积的4倍呀（如下图所示）。想不明白，请教一下。
<img width="768" alt="q" src="https://github.com/YvanYin/Metric3D/assets/77491386/5439eaf4-beea-4528-bd5d-dcb6626d5817">

**Comment by JUGGHM** [comment]
你好，论文中的S不是面积，是边长
