### ISSUE TITLE
how to predict depth of images from different at the same time  

### ISSUE THREAD

**Issue by 942411526** [YvanYin/Metric3D#23]
Dear author,
I want to predict the depth from many images captured by different cameras. it will be spend long time if we put a single image to the model every time. So I want to put a batch of images to the model one time, but there is a problem, the camera has different intrinsics, and cannot use a normal cameral model. I have tried to the inference function, but  miss in "get_func('mono.model.model_pipelines.' + model_type)(cfg)"

**Comment by JUGGHM** [comment]
> Dear author, I want to predict the depth from many images captured by different cameras. it will be spend long time if we put a single image to the model every time. So I want to put a batch of images to the model one time, but there is a problem, the camera has different intrinsics, and cannot use a normal cameral model. I have tried to the inference function, but miss in "get_func('mono.model.model_pipelines.' + model_type)(cfg)"

I hope [this issue](https://github.com/YvanYin/Metric3D/issues/20#issue-1931592836) would help. By the way, do not forget to set the [launcher](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/tools/test_scale_cano.py#L83C5-L83C32) to make the codes execute in DDP mode.

**Comment by YvanYin** [comment]
> Dear author, I want to predict the depth from many images captured by different cameras. it will be spend long time if we put a single image to the model every time. So I want to put a batch of images to the model one time, but there is a problem, the camera has different intrinsics, and cannot use a normal cameral model. I have tried to the inference function, but miss in "get_func('mono.model.model_pipelines.' + model_type)(cfg)"

The code supports different camera settings in a batch. You only need to enclose the original camera information in JSON file. 
Please see this: https://github.com/YvanYin/Metric3D/blob/main/mono/utils/custom_data.py
