### ISSUE TITLE
ScanNet evaluation set

### ISSUE THREAD

**Issue by markkua** [YvanYin/Metric3D#24]
Hello, thanks for your great work. Could you let me know which subset of ScanNet you used for evaluation? I would be even better if you could share the file list.

**Comment by JUGGHM** [comment]
> Hello, thanks for your great work. Could you let me know which subset of ScanNet you used for evaluation? I would be even better if you could share the file list.

Thank you for your interest. We randomlly sample 700 images from the validation set. Unfortunately, we cannot share the file list now. If you need to make a comparison, just use another random sampled validation set and report your own results.
