### ISSUE TITLE
Question about canonical camera parameters

### ISSUE THREAD

**Issue by RookieHuang** [YvanYin/Metric3D#25]
Thanks for your great work.
When I dive into the code about canonical ratio,I found that the canonical ratio was normalized by the real camera focal length x(f_x) in the part of preparing gt depth label(transform.py),but it was normalized by (f_x+f_y)/2 in the test script(do_test.py).Could the inconsistency lead to deep confusion?
Looking forward to your reply!

**Comment by JUGGHM** [comment]
> Thanks for your great work. When I dive into the code about canonical ratio,I found that the canonical ratio was normalized by the real camera focal length x(f_x) in the part of preparing gt depth label(transform.py),but it was normalized by (f_x+f_y)/2 in the test script(do_test.py).Could the inconsistency lead to deep confusion? Looking forward to your reply!

In transform.py, the transformation is used for training, where we resize the image while keeping the aspect ratio. The resize factor is defined according to the ratio of x-axis intrinsic ratio.

**Comment by RookieHuang** [comment]
Thanks for your reply!
