### ISSUE TITLE
Reproducibility Zero-shot results

### ISSUE THREAD

**Issue by lpiccinelli-eth** [YvanYin/Metric3D#26]
Thank you for your work!

I can reproduce your results on KITTI and NYU, but not on the other zero-shot datasets.
I tried the 3 different configs you provided under `mono/config`, but I could not reproduce them.
I would like to know what config and pre-processing you are using, especially the `crop_size` and the canonical focal length.

Thank you in advance.

**Comment by JUGGHM** [comment]
> Thank you for your work!
> 
> I can reproduce your results on KITTI and NYU, but not on the other zero-shot datasets. I tried the 3 different configs you provided under `mono/config`, but I could not reproduce them. I would like to know what config and pre-processing you are using, especially the `crop_size` and the canonical focal length.
> 
> Thank you in advance.

Thank you for your interest! Several users have addressed similar concerns.

We find that the released checkpoint (750k) might have mismatching performance on some of the datasets. The reported results in the paper actually came from earlier checkpoints. Before code releasing, we only checked NYU and KITTI performance. 

For Eth3d this checkpoint should have around 10%  error (scale aligned) .  
config size = (544, 992)

For DIODE it is around 26%.
# indoor (544, 928), outdoor: (768, 1088)

But good news is that we will release more powerful transformer-based checkpoints in the future, as well as smaller models. This might take some time.

**Comment by lpiccinelli-eth** [comment]
Thank you for the prompt reply and I appreciate your transparency.
Do you mind sharing the config used while testing on NuScenes, too? Thanks!

**Comment by JUGGHM** [comment]
> Thank you for the prompt reply and I appreciate your transparency. Do you mind sharing the config used while testing on NuScenes, too? Thanks!

It is (512, 992)

**Comment by shawnricecake** [comment]
could you guys share how to get on zero-shot results? @JUGGHM  @lpiccinelli-eth
