### ISSUE TITLE
请问一下关于test结果的问题：w/o match、median match、global match这三者是什么意思？以及delta代表的含义是什么？ 

### ISSUE THREAD

**Issue by zaoruis** [YvanYin/Metric3D#27]
![361eff3be0d834862aa1fa10da0598a](https://github.com/YvanYin/Metric3D/assets/148841880/e7d26e0a-fa01-4491-8a3f-f5bff63c32f5)
为什么出现部分delta为0的情况

**Comment by JUGGHM** [comment]
网络输出的尺度误差较大
（1）Global，根据GT，全局拟合一个scale和一个shift因子，将尺度align到gt上。最终输出 pred_hat = pred * scale + shift 
（2）Median，根据GT和pred的median仅仅拟合一个scale因子，最终输出 最终输出 pred_hat = pred * scale

**Comment by JUGGHM** [comment]
> ![361eff3be0d834862aa1fa10da0598a](https://user-images.githubusercontent.com/148841880/277555001-e7d26e0a-fa01-4491-8a3f-f5bff63c32f5.png) 为什么出现部分delta为0的情况

delta1, 2, 3 是相对误差指标，详见[代码](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/utils/avg_meter.py#L379)

**Comment by wenjie-yuan** [comment]
> 网络输出的尺度误差较大 （1）Global，根据GT，全局拟合一个scale和一个shift因子，将尺度align到gt上。最终输出 pred_hat = pred * scale + shift （2）Median，根据GT和pred的median仅仅拟合一个scale因子，最终输出 最终输出 pred_hat = pred * scale

无监督里面median match、global match还是蛮常见的，毕竟训练时没有实际的距离参考，评估时增加这两项指标还是方便和有监督对比；但是作为有监督，或者实际落地的情况考虑，用到验证/测试集的GT值来算scale和一个shift是不是不太合理，因为推理时没有GT
（1）这方面怎么解释？SLAM或者什么下游任务可以用测试集GT吗？
（2）有尝试用训练集来拟合scale和shift因子吗？训练集GT可以用的，有的话指标怎么样？
总感觉w/o match精度低，如果是有监督，还是没有解决Domain的问题

**Comment by JUGGHM** [comment]
> > 网络输出的尺度误差较大 （1）Global，根据GT，全局拟合一个scale和一个shift因子，将尺度align到gt上。最终输出 pred_hat = pred * scale + shift （2）Median，根据GT和pred的median仅仅拟合一个scale因子，最终输出 最终输出 pred_hat = pred * scale
> 
> 无监督里面median match、global match还是蛮常见的，毕竟训练时没有实际的距离参考，评估时增加这两项指标还是方便和有监督对比；但是作为有监督，或者实际落地的情况考虑，用到验证/测试集的GT值来算scale和一个shift是不是不太合理，因为推理时没有GT （1）这方面怎么解释？SLAM或者什么下游任务可以用测试集GT吗？ （2）有尝试用训练集来拟合scale和shift因子吗？训练集GT可以用的，有的话指标怎么样？ 总感觉w/o match精度低，如果是有监督，还是没有解决Domain的问题

从落地角度讲，不应该这么做。

**Comment by YvanYin** [comment]
> pred * scale + shift 中scale 和shift 是怎么计算出来的？下面这样吗？ scale = median(GT_values) / median(estimated_depth_values) shift = mean(GT_values) - mean(estimated_depth_values) * scale

不是的。直接做最小二乘拟合得到 scale和shift。 可以参照 https://github.com/aim-uofa/AdelaiDepth/blob/d85181982bd2a42c912fd8a48c40cdc7ec71d553/LeReS/Minist_Test/lib/test_utils.py#L230  这个函数。
