### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by zaoruis** [YvanYin/Metric3D#28]
很抱歉再次打扰您，第一张图是直接使用在github下载的图片，就是初始的nyu_demo图的测试结果；第二张图是我从nyu数据集挑了10的测试结果。仅仅只是换了测试图，w/o match当中的delta却均为0，而median match和global match是正常数值，这种结果是否具有可解释性呢？

![Uploading 30d8fbf391e42f23b56acf9a0192ba9.png…]()
![361eff3be0d834862aa1fa10da0598a](https://github.com/YvanYin/Metric3D/assets/148841880/21171478-2119-427c-a933-e4d99c925471)

**Comment by JUGGHM** [comment]
不太正常，NYU里面的数据不会有这么大的尺度误差
