### ISSUE TITLE
How to combine Metric3d and Droid-slam？

### ISSUE THREAD

**Issue by Zhangc0715** [YvanYin/Metric3D#29]
Hello, I ran Metric3d and Droid-slam separately yesterday, but I have a question. Can you provide some ideas on how to combine the two? The depth map is estimated through Metric3d and then input into Droid- Is auxiliary modeling performed in slam? Is this done to give the map a scale?

**Comment by ckLibra** [comment]
Hi, we initialize the droid's depth from metric3D, and using the rgbd mode in DROID-SLAM, i.e. constraining depth optimization not far from metric3D's prediction.
