### ISSUE TITLE
the label_scale_factor mean depth scale or the pixel scale of the camera ?

### ISSUE THREAD

**Issue by 942411526** [YvanYin/Metric3D#30]
**the label_scale_factor** mean depth scale or the pixel scale of the camera? or any others?

**Comment by JUGGHM** [comment]
> **the label_scale_factor** mean depth scale or the pixel scale of the camera? or any others?

It is an image-level scale factor from the raw camera space to the canonical space.

**Comment by 942411526** [comment]
we add the depth module to our model, but the output from depth module is so small , the max is 5.04 (intrinsic[1000,1000,160,80])

**Comment by JUGGHM** [comment]
> we add the depth module to our model, but the output from depth module is so small , the max is 5.04 (intrinsic[1000,1000,160,80])

The image size looks fairly small. You could set the [crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C15) in the config file to a smaller one.

**Comment by 942411526** [comment]
I do it, but there are problems.  I set the img_size=(480, 854),  focal_length=1000.0, (intrinsic[1000,1000,427,240])  the max  value in the depth maps is tensor(24.0547, device='cuda:0'), but tested same image in your test. sh  the max the is 260.7979. ( the setting is same) I can't understand.

**Comment by JUGGHM** [comment]
> I do it, but there are problems. I set the img_size=(480, 854), focal_length=1000.0, (intrinsic[1000,1000,427,240]) the max value in the depth maps is tensor(24.0547, device='cuda:0'), but tested same image in your test. sh the max the is 260.7979. ( the setting is same) I can't understand.

Oh I think we should never change ```image_size```, which means the image size during training (for the canonical space camera). We shall change ```crop_size``` instead.

**Comment by 942411526** [comment]
I see.  I change the crop_size to 480, 854

**Comment by 942411526** [comment]
Maybe I know what's going on. I normalized the image before I typed it into transform_test_data_scalecano. I multiplied it by 255 and the maximum value of the output depth map became 255. But is it right? Don't you need to normalize the image before entering transform_test_data_scalecano? Do you need to normalize when you train?

**Comment by JUGGHM** [comment]
> I do it, but there are problems. I set the img_size=(480, 854), focal_length=1000.0, (intrinsic[1000,1000,427,240]) the max value in the depth maps is tensor(24.0547, device='cuda:0'), but tested same image in your test. sh the max the is 260.7979. ( the setting is same) I can't understand.

Here do you mean that you have a groundtruth "depth map"? If it is an outdoor image, the model is likely to predict very large values for very far backgrounds.

**Comment by 942411526** [comment]
no without gt ,we predict a  drive image

**Comment by JUGGHM** [comment]
> no without gt ,we predict a drive image

If the pixel with 260-meter depth lies at very ranged regions, it could be possible.

**Comment by 942411526** [comment]
what is the depth range when you train the depth network?  we add the depth network  to our model and freeze,  the whole model will be difficult to train if without normalization the depth map

**Comment by JUGGHM** [comment]
> what is the depth range when you train the depth network? we add the depth network to our model and freeze, the whole model will be difficult to train if without normalization the depth map

The [bin-based prediction](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/model/decode_heads/HourGlassDecoder.py#L257C9-L257C22) is ranged in (0.3, 150), defined [here](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L20C32-L20C32). Afterwards a refine [module](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/model/decode_heads/HourGlassDecoder.py#L264) is imposed, so theoratically there is no such range for the final output. In the meanwhile sky is defined to be 180m. Somehow a small propotion of backgrounds might be even "farther" than sky, under this setting.

**Comment by 942411526** [comment]
> > what is the depth range when you train the depth network? we add the depth network to our model and freeze, the whole model will be difficult to train if without normalization the depth map
> 
> The [bin-based prediction](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/model/decode_heads/HourGlassDecoder.py#L257C9-L257C22) is ranged in (0.3, 150), defined [here](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L20C32-L20C32). Afterwards a refine [module](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/model/decode_heads/HourGlassDecoder.py#L264) is imposed, so theoratically there is no such range for the final output. In the meanwhile sky is defined to be 180m. Somehow a small propotion of backgrounds might be even "farther" than sky, under this setting.
did you normalization the depth to (0,1)?  when you train the depth network to calculate the depth loss

**Comment by JUGGHM** [comment]
> > > what is the depth range when you train the depth network? we add the depth network to our model and freeze, the whole model will be difficult to train if without normalization the depth map
> > 
> > 
> > The [bin-based prediction](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/model/decode_heads/HourGlassDecoder.py#L257C9-L257C22) is ranged in (0.3, 150), defined [here](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L20C32-L20C32). Afterwards a refine [module](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/model/decode_heads/HourGlassDecoder.py#L264) is imposed, so theoratically there is no such range for the final output. In the meanwhile sky is defined to be 180m. Somehow a small propotion of backgrounds might be even "farther" than sky, under this setting.
> > did you normalization the depth to (0,1)?  when you train the depth network to calculate the depth loss

Bin-based prediction should be regarded as such normalization. It describes a probability distribution upon pre-defined depth bins.
