### ISSUE TITLE
深度丢失

### ISSUE THREAD

**Issue by Minnchong** [YvanYin/Metric3D#32]
作者大大，您好！在运行test.sh的时候无法获取深度
![Uploading 微信图片_20231106170420.png…]()

**Comment by Minnchong** [comment]
missing gt_depth, only save visualizations...

**Comment by JUGGHM** [comment]
> missing gt_depth, only save visualizations...

无法获取深度是什么意思？这只说明没有groundtruth。另外图好像看不到。

**Comment by Minnchong** [comment]
很抱歉没有及时回复您，我在in-the-wild-mode一段介绍的理解是，在检测数据集以外的图像时，如果可以正确的设定intrinsic，那么在运行test.sh时能够获得图像的绝对深度，也就是以米为单位的距离。但在我模拟设定了一个intrinsic，针对您提供的wild_demo运行test.sh时，结果只显示了深度可视化图像，无法获得绝对深度。我想咨询一下，是我的代码理解有误吗？

**Comment by Minnchong** [comment]
![微信图片_20231106170420](https://github.com/YvanYin/Metric3D/assets/86814435/8318a7a5-5d26-47db-a7cb-e5c4dbaeb4dc)

**Comment by Minnchong** [comment]
![david-kohler-VFRTXGw1VjU-unsplash_merge](https://github.com/YvanYin/Metric3D/assets/86814435/a49c047c-5d20-46f6-8682-81d388d8c85f)

**Comment by Minnchong** [comment]
@JUGGHM

**Comment by JUGGHM** [comment]
> @JUGGHM

（1）是有绝对深度的，你可以使用https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/utils/visualization.py#L11 保存十六位深度图。或者也可以检查 [pred_depth](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/utils/do_test.py#L299) 的数值，单位是米
（2）最下面那个橙色的是对真值的可视化。这张图没有真值就没有可视化。

**Comment by Minnchong** [comment]
非常感谢您的帮助
