### ISSUE TITLE
代码运行遇到bug

### ISSUE THREAD

**Issue by Linkersem** [YvanYin/Metric3D#33]
作者大大您好，我按照“[In-the-Wild Mode](https://github.com/YvanYin/Metric3D#in-the-wild-mode)”的流程跑代码，但是出现了一个错误，如下所示 @JUGGHM 
![image](https://github.com/YvanYin/Metric3D/assets/49711774/a3c7ea09-f00c-429f-bb3d-8ff0cefccc72)

**Comment by JUGGHM** [comment]
你是否改过代码？上面几行对这个变量是赋值了的。in the wild mode 应该是false

**Comment by Linkersem** [comment]
没有的，我直接拉下来然后把图片放到对应的文件夹，然后改了一下内参，就没有修改了

**Comment by JUGGHM** [comment]
> 没有的，我直接拉下来然后把图片放到对应的文件夹，然后改了一下内参，就没有修改了

那你把它置成false就行了
