### ISSUE TITLE
Test case

### ISSUE THREAD

**Issue by dasda-asd** [YvanYin/Metric3D#34]
Can I give you a code to test a single image?
I would appreciate your reply.

**Comment by JUGGHM** [comment]
> Can I give you a code to test a single image? I would appreciate your reply.

Thank you for your interest. But what do you mean by "giving us a code"?

**Comment by dasda-asd** [comment]
> > Can I give you a code to test a single image? I would appreciate your reply.
> 
> Thank you for your interest. But what do you mean by "giving us a code"?

Yes. Give a simple test code, including loading the model, loading the weight file, uploading the image data, saving the results, and so on

**Comment by dasda-asd** [comment]
> > Can I give you a code to test a single image? I would appreciate your reply.
> 
> Thank you for your interest. But what do you mean by "giving us a code"?

I'd appreciate it if you could.

**Comment by JUGGHM** [comment]
> > > Can I give you a code to test a single image? I would appreciate your reply.
> > 
> > 
> > Thank you for your interest. But what do you mean by "giving us a code"?
> 
> I'd appreciate it if you could.

You could post/upload it here if you like. We would test it later if time available. 
But I think our test scripts have covered in-the-wild mode for any unlabeled data.
