### ISSUE TITLE
when release the Stronger models and tiny models

### ISSUE THREAD

**Issue by qiuhaining** [YvanYin/Metric3D#35]
Very solid work, and i hope to try the Stronger models and how to use to slam or others,can you release relative codes,thanks!

**Comment by JUGGHM** [comment]
> Very solid work, and i hope to try the Stronger models and how to use to slam or others,can you release relative codes,thanks!

Models are still under training, we expect to finish this part before this year ends or the next spring.

**Comment by qiuhaining** [comment]
> > Very solid work, and i hope to try the Stronger models and how to use to slam or others,can you release relative codes,thanks!
> 
> Models are still under training, we expect to finish this part before this year ends or the next spring.

OK. What will be your focus next?

**Comment by YvanYin** [comment]
We will release stronger and tiny models and training codes soon.

**Comment by YvanYin** [comment]
@qiuhaining more models are released. Training code will be released this week.
