### ISSUE TITLE
A question about the depth meaning，thanks！

### ISSUE THREAD

**Issue by coldcode1** [YvanYin/Metric3D#36]
hello，Thanks for your great work！ I have a small question,for each pixel point， does the predicted depth mean the euclidean distance from the surface point of the object to the center of the camera's optical center , or the vertical distance to the image?

**Comment by JUGGHM** [comment]
> hello，Thanks for your great work！ I have a small question,for each pixel point， does the predicted depth mean the euclidean distance from the surface point of the object to the center of the camera's optical center , or the vertical distance to the image?

Thank you for your interest! It should be the vertical distance to the plane where the optical center lies on and parallel to the camera imaging plane .
