### ISSUE TITLE
输出显示没有gt_depth

### ISSUE THREAD

**Issue by Linkersem** [YvanYin/Metric3D#37]
@JUGGHM  作者大大您好，我有俩个问题想请教一下；
1、我有一个室内的数据集，我似乎应该跑dataset mode，但是我注意到这个mode需要深度数据作为输入，这个让我很困惑？如果我确实应该跑这个模式，我应该怎么做呢？
2、我用这个室内的数据集跑in-the-wild模式，我设置了内参，代码也可以正常的跑完，但是显示缺少gt_depth数据，这个是哪里有问题吗？我看到有和我类似问题的， 但是那个回复并没有解释我的疑惑，所以我想再进一步请教一下
![image](https://github.com/YvanYin/Metric3D/assets/49711774/a1cbfeeb-a109-47c6-ac8f-d5ea0e39002c)

![image](https://github.com/YvanYin/Metric3D/assets/49711774/81c580c0-8bcc-400b-bee1-286ce2d69c54)

**Comment by JUGGHM** [comment]
> @JUGGHM 作者大大您好，我有俩个问题想请教一下； 1、我有一个室内的数据集，我似乎应该跑dataset mode，但是我注意到这个mode需要深度数据作为输入，这个让我很困惑？如果我确实应该跑这个模式，我应该怎么做呢？ 2、我用这个室内的数据集跑in-the-wild模式，我设置了内参，代码也可以正常的跑完，但是显示缺少gt_depth数据，这个是哪里有问题吗？我看到有和我类似问题的， 但是那个回复并没有解释我的疑惑，所以我想再进一步请教一下 ![image](https://user-images.githubusercontent.com/49711774/284777326-a1cbfeeb-a109-47c6-ac8f-d5ea0e39002c.png)
> 
> ![image](https://user-images.githubusercontent.com/49711774/284777556-81c580c0-8bcc-400b-bee1-286ce2d69c54.png)

gt_depth指深度图真值（从LiDAR/红外rgbd相机/mvs获得），如果需要使用深度图真值测量误差，请先配置其json文件。一般in-the-wild模式使用时没有深度图针织。

**Comment by JUGGHM** [comment]
> ok，我明白了，谢谢您的回复，我想再请问一下，目前这个方法支持鱼眼相机的深度估计吗？

当前模型可以直接inference出一个大致的深度图，但尺度正确性无法保证
如果追求一致性的话建议先fisheye->pinhole再inference
