### ISSUE TITLE
In-the-Wild Mode，水平场景真值5米，预测16.5米；倾斜场景人身高5米。

### ISSUE THREAD

**Issue by jay25208** [YvanYin/Metric3D#38]
我遇到绝对深度有偏差大的问题，请教一下是配置错误还是模型泛化问题。 @JUGGHM 
背景：用例是在室内停车场水平拍摄一面墙，距离墙面真值已知。
过程：根据Readme中In-the-Wild Mode指导更换内参为[520, 520, 472.4, 276.2]（像素单位），输入图像分辨率960 * 540。相机原分辨率是1920 * 1080，内参是[520, 520, 472.4, 276.2]的2 倍。
问题：距离墙面真值5米，预测16.5米，图片中基本只有左侧有车头，天花板有些架子。真值8米，预测是21.4米，图片背景类似，左侧有2个车头。
测距不准是什么原因呢?是配置错误还是模型泛化问题。
另外论文里统一到1000焦距，这是um单位，还是像素单位？而代码里配置的'intrinsic'参数是像素单位吧？

此外，还在室内顶装俯仰角大概20°，存在人的身高偏差大，为5米左右。同张图不同远近的人身高是接近的。假设人的身高是1.7米。这个偏差是什么造成的？

感谢解答！

**Comment by JUGGHM** [comment]
> 我遇到绝对深度有偏差大的问题，请教一下是配置错误还是模型泛化问题。 @JUGGHM 背景：用例是在室内停车场水平拍摄一面墙，距离墙面真值已知。 过程：根据Readme中In-the-Wild Mode指导更换内参为[520, 520, 472.4, 276.2]（像素单位），输入图像分辨率960_540。相机原分辨率是1920_1080，内参是[520, 520, 472.4, 276.2]的2 倍。 问题：距离墙面真值5米，预测16.5米，图片中基本只有左侧有车头，天花板有些架子。真值8米，预测是21.4米，图片背景类似，左侧有2个车头。 测距不准是什么原因呢?是配置错误还是模型泛化问题。 另外论文里统一到1000焦距，这是um单位，还是像素单位？而代码里配置的'intrinsic'参数是像素单位吧？
> 
> 此外，还在室内顶装俯仰角大概20°，存在人的身高偏差大，为5米左右。同张图不同远近的人身高是接近的。假设人的身高是1.7米。这个偏差是什么造成的？
> 
> 感谢解答！

感谢关注：
问题一：我想确认下是否为：输入整个程序的图像大小为960540，内参改为[520, 520, 472.4, 276.2]？这样的话是正确的配置。
另外宽，高，cx，cy可否确认有没有弄反？看上去c=472对应960，这个是否为宽度？一般我们训练的图像 宽>高
此外，建议这里[crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C29)也改为 540, 960。focal length都是以像素为单位

问题二：顶装本身数据较少，尺度可能会有较大偏差。如果相机是鱼眼的话可能偏差更大。

如果发现网络出的尺度有比较恒定的尺度误差 （如为真值的一半左右），权宜之计是将深度整体乘一个因子。如有办法获得深度真值，可以生成json文件并用数据集模式获得一个粗糙估计的因子。我们现在也在尝试加大模型/数据，采用不同的方法缓解部分数据集上尺度不鲁棒的现象。

**Comment by JUGGHM** [comment]
> > > 我遇到绝对深度有偏差大的问题，请教一下是配置错误还是模型泛化问题。 @JUGGHM 背景：用例是在室内停车场水平拍摄一面墙，距离墙面真值已知。 过程：根据Readme中In-the-Wild Mode指导更换内参为[520, 520, 472.4, 276.2]（像素单位），输入图像分辨率960_540。相机原分辨率是1920_1080，内参是[520, 520, 472.4, 276.2]的2 倍。 问题：距离墙面真值5米，预测16.5米，图片中基本只有左侧有车头，天花板有些架子。真值8米，预测是21.4米，图片背景类似，左侧有2个车头。 测距不准是什么原因呢?是配置错误还是模型泛化问题。 另外论文里统一到1000焦距，这是um单位，还是像素单位？而代码里配置的'intrinsic'参数是像素单位吧？
> > > 此外，还在室内顶装俯仰角大概20°，存在人的身高偏差大，为5米左右。同张图不同远近的人身高是接近的。假设人的身高是1.7米。这个偏差是什么造成的？
> > > 感谢解答！
> > 
> > 
> > 感谢关注： 问题一：我想确认下是否为：输入整个程序的图像大小为960540，内参改为[520, 520, 472.4, 276.2]？这样的话是正确的配置。 另外宽，高，cx，cy可否确认有没有弄反？看上去c=472对应960，这个是否为宽度？一般我们训练的图像 宽>高 此外，建议这里[crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C29)也改为 540, 960。focal length都是以像素为单位
> > 问题二：顶装本身数据较少，尺度可能会有较大偏差。如果相机是鱼眼的话可能偏差更大。
> > 如果发现网络出的尺度有比较恒定的尺度误差 （如为真值的一半左右），权宜之计是将深度整体乘一个因子。如有办法获得深度真值，可以生成json文件并用数据集模式获得一个粗糙估计的因子。我们现在也在尝试加大模型/数据，采用不同的方法缓解部分数据集上尺度不鲁棒的现象。
> 
> 感谢解答！ 960 * 540对应width * height，其内参[520, 520, 472.4, 276.2]对应[fx, fy, cx, cy], 内参这个四个参数按分辨率缩放，而1920 * 1080对应[1040, 1040, 944.8, 552.4]。 其他建议，我后续尝试后再回复您。
> 
> 按你建议改这里[crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C29)也改为 540, 960后，会报如下错误：
> 
> ```
>  File "/data1/12-depth/02-Metric3D/Metric3D-main/mono/model/decode_heads/HourGlassDecoder.py", line 84, in forward
>     x = torch.cat((self.upsample(x), ref_feature[2]), 1)
> RuntimeError: Sizes of tensors must match except in dimension 2. Got 33 and 32 (The offending index is 0)
> ```
> 
> 请问：img_size和crop_size 含义是什么？该怎么设置，避免上述报错。

（1）只能改crop_size，绝对不要改canonical space下的[img_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L16)

canonical space是metric 3d的核心方法，旨在让网络在同一焦距空间下预测深度，因此不能随意变动

（2）crop_size是希望输入网络的图像大小，长宽应接近图像大小，且为32的整数倍（ConvNeXt下采样32倍）。否则会报你提到的错误。如果不是，应该找比较接近的resolution。

**Comment by jay25208** [comment]
> > > > 我遇到绝对深度有偏差大的问题，请教一下是配置错误还是模型泛化问题。 @JUGGHM 背景：用例是在室内停车场水平拍摄一面墙，距离墙面真值已知。 过程：根据Readme中In-the-Wild Mode指导更换内参为[520, 520, 472.4, 276.2]（像素单位），输入图像分辨率960_540。相机原分辨率是1920_1080，内参是[520, 520, 472.4, 276.2]的2 倍。 问题：距离墙面真值5米，预测16.5米，图片中基本只有左侧有车头，天花板有些架子。真值8米，预测是21.4米，图片背景类似，左侧有2个车头。 测距不准是什么原因呢?是配置错误还是模型泛化问题。 另外论文里统一到1000焦距，这是um单位，还是像素单位？而代码里配置的'intrinsic'参数是像素单位吧？
> > > > 此外，还在室内顶装俯仰角大概20°，存在人的身高偏差大，为5米左右。同张图不同远近的人身高是接近的。假设人的身高是1.7米。这个偏差是什么造成的？
> > > > 感谢解答！
> > > 
> > > 
> > > 感谢关注： 问题一：我想确认下是否为：输入整个程序的图像大小为960540，内参改为[520, 520, 472.4, 276.2]？这样的话是正确的配置。 另外宽，高，cx，cy可否确认有没有弄反？看上去c=472对应960，这个是否为宽度？一般我们训练的图像 宽>高 此外，建议这里[crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C29)也改为 540, 960。focal length都是以像素为单位
> > > 问题二：顶装本身数据较少，尺度可能会有较大偏差。如果相机是鱼眼的话可能偏差更大。
> > > 如果发现网络出的尺度有比较恒定的尺度误差 （如为真值的一半左右），权宜之计是将深度整体乘一个因子。如有办法获得深度真值，可以生成json文件并用数据集模式获得一个粗糙估计的因子。我们现在也在尝试加大模型/数据，采用不同的方法缓解部分数据集上尺度不鲁棒的现象。
> > 
> > 
> > 感谢解答！ 960 * 540对应width * height，其内参[520, 520, 472.4, 276.2]对应[fx, fy, cx, cy], 内参这个四个参数按分辨率缩放，而1920 * 1080对应[1040, 1040, 944.8, 552.4]。 其他建议，我后续尝试后再回复您。
> > 按你建议改这里[crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C29)也改为 540, 960后，会报如下错误：
> > ```
> >  File "/data1/12-depth/02-Metric3D/Metric3D-main/mono/model/decode_heads/HourGlassDecoder.py", line 84, in forward
> >     x = torch.cat((self.upsample(x), ref_feature[2]), 1)
> > RuntimeError: Sizes of tensors must match except in dimension 2. Got 33 and 32 (The offending index is 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问：img_size和crop_size 含义是什么？该怎么设置，避免上述报错。
> 
> （1）只能改crop_size，绝对不要改canonical space下的[img_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L16)
> 
> canonical space是metric 3d的核心方法，旨在让网络在同一焦距空间下预测深度，因此不能随意变动
> 
> （2）crop_size是希望输入网络的图像大小，长宽应接近图像大小，且为32的整数倍（ConvNeXt下采样32倍）。否则会报你提到的错误。如果不是，应该找比较接近的resolution。

谢谢解答。我修改了crop_size为(544, 960)，是32整数倍可以推理。
对比crop_size为默认的(544, 960)和修改后的(544, 960)，从输出ply文件点云看起来，深度在很接近，只是更深了一点。所以，crop_size参数还不是造成深度偏差大的原因。我后续再分析，谢谢!

**Comment by jay25208** [comment]
> 您好，该如何从深度图中读取深度值呢？

输出文件没有深度图，是从输出ply文件点云看深度的。

**Comment by JUGGHM** [comment]
> > 您好，该如何从深度图中读取深度值呢？
> 
> 输出文件没有深度图，是从输出ply文件点云看深度的。

可以把点云投到图像上保存为深度图，然后用generate json生成数据集；之后再用数据集模式粗略估计因子；一般同一个数据集（场景、相机）尺度因子比较接近

**Comment by JUGGHM** [comment]
> > > > > 我遇到绝对深度有偏差大的问题，请教一下是配置错误还是模型泛化问题。 @JUGGHM 背景：用例是在室内停车场水平拍摄一面墙，距离墙面真值已知。 过程：根据Readme中In-the-Wild Mode指导更换内参为[520, 520, 472.4, 276.2]（像素单位），输入图像分辨率960_540。相机原分辨率是1920_1080，内参是[520, 520, 472.4, 276.2]的2 倍。 问题：距离墙面真值5米，预测16.5米，图片中基本只有左侧有车头，天花板有些架子。真值8米，预测是21.4米，图片背景类似，左侧有2个车头。 测距不准是什么原因呢?是配置错误还是模型泛化问题。 另外论文里统一到1000焦距，这是um单位，还是像素单位？而代码里配置的'intrinsic'参数是像素单位吧？
> > > > > 此外，还在室内顶装俯仰角大概20°，存在人的身高偏差大，为5米左右。同张图不同远近的人身高是接近的。假设人的身高是1.7米。这个偏差是什么造成的？
> > > > > 感谢解答！
> > > > 
> > > > 
> > > > 感谢关注： 问题一：我想确认下是否为：输入整个程序的图像大小为960540，内参改为[520, 520, 472.4, 276.2]？这样的话是正确的配置。 另外宽，高，cx，cy可否确认有没有弄反？看上去c=472对应960，这个是否为宽度？一般我们训练的图像 宽>高 此外，建议这里[crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C29)也改为 540, 960。focal length都是以像素为单位
> > > > 问题二：顶装本身数据较少，尺度可能会有较大偏差。如果相机是鱼眼的话可能偏差更大。
> > > > 如果发现网络出的尺度有比较恒定的尺度误差 （如为真值的一半左右），权宜之计是将深度整体乘一个因子。如有办法获得深度真值，可以生成json文件并用数据集模式获得一个粗糙估计的因子。我们现在也在尝试加大模型/数据，采用不同的方法缓解部分数据集上尺度不鲁棒的现象。
> > > 
> > > 
> > > 感谢解答！ 960 * 540对应width * height，其内参[520, 520, 472.4, 276.2]对应[fx, fy, cx, cy], 内参这个四个参数按分辨率缩放，而1920 * 1080对应[1040, 1040, 944.8, 552.4]。 其他建议，我后续尝试后再回复您。
> > > 按你建议改这里[crop_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L21C5-L21C29)也改为 540, 960后，会报如下错误：
> > > ```
> > >  File "/data1/12-depth/02-Metric3D/Metric3D-main/mono/model/decode_heads/HourGlassDecoder.py", line 84, in forward
> > >     x = torch.cat((self.upsample(x), ref_feature[2]), 1)
> > > RuntimeError: Sizes of tensors must match except in dimension 2. Got 33 and 32 (The offending index is 0)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 请问：img_size和crop_size 含义是什么？该怎么设置，避免上述报错。
> > 
> > 
> > （1）只能改crop_size，绝对不要改canonical space下的[img_size](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/configs/HourglassDecoder/convlarge.0.3_150.py#L16)
> > canonical space是metric 3d的核心方法，旨在让网络在同一焦距空间下预测深度，因此不能随意变动
> > （2）crop_size是希望输入网络的图像大小，长宽应接近图像大小，且为32的整数倍（ConvNeXt下采样32倍）。否则会报你提到的错误。如果不是，应该找比较接近的resolution。
> 
> 谢谢解答。我修改了crop_size为(544, 960)，是32整数倍可以推理。 对比crop_size为默认的(544, 1216)和修改后的(544, 960)，从输出ply文件点云看起来，深度在很接近，只是更深了一点。所以，crop_size参数还不是造成深度偏差大的原因。我后续再分析，谢谢!

如果有办法得到少量深度图真值的话，可以用我们的generate json脚本生成数据集；之后再用数据集模式粗略估计因子；一般同一个数据集（场景、相机）尺度因子比较接近

**Comment by wellneck** [comment]
I also encountered the same problem, it seems that the model predictions have a scale error of about 3 with the scene im interested

**Comment by xubosyj** [comment]
> > 您好，该如何从深度图中读取深度值呢？
> 
> 输出文件没有深度图，是从输出ply文件点云看深度的。

不好意思，想问问点云如何看深度呢？还有，比如导入meshlab中我可以得到目标两点的距离，那么和真实估计的scale关系是什么。感谢

**Comment by jay25208** [comment]
> > > 您好，该如何从深度图中读取深度值呢？
> > 
> > 
> > 输出文件没有深度图，是从输出ply文件点云看深度的。
> 
> 不好意思，想问问点云如何看深度呢？还有，比如导入meshlab中我可以得到目标两点的距离，那么和真实估计的scale关系是什么。感谢

z值是深度。此外，可以把模型输出转u16格式保存成深度图。
第二个问题，我也不清楚，和模型泛化性和原理有关，需作者解答。

**Comment by jay25208** [comment]
我发现我们的用例中类似NYUv2的场景，即室内、水平视角，绝对深度效果基本正常。
我推测其他场景效果不佳，可能是训练样本和我们测试用例差异较大，模型泛化性的问题。
打算复现训练，后加我们场景样本后再验证。
谢谢作者的帮助，感谢！

**Comment by jay25208** [comment]
我发现我们的用例中类似NYUv2的场景，即室内、水平视角，绝对深度效果基本正常。
我推测其他场景效果不佳，可能是训练样本和我们测试用例差异较大，模型泛化性的问题。
打算复现训练，后加我们场景样本后再验证。
谢谢作者的帮助，感谢！
