### ISSUE TITLE
Fine tuning the model on NYU datasets

### ISSUE THREAD

**Issue by lgzz** [YvanYin/Metric3D#39]
Thanks for your amazing work!
1) I really want to know the performance if you fine tuning the model on NYU datasets, I guess you can win the championship.
Have you ever tried this? If so, please tell me!
2) Will you make the training code available? Thank you very much!
3) I am confused about the unit of fx and fy, is it (mm) or (pixels)?
Looking forward to your reply!

**Comment by lgzz** [comment]
Thanks!

**Comment by Ghul-huan** [comment]
Thank you for your work. Although you have already answered, I still want to ask whether the training code will be useful in the next few months

**Comment by YvanYin** [comment]
We will release the code this week. @Ghul-huan
