### ISSUE TITLE
NYU scene reconstruction

### ISSUE THREAD

**Issue by kwea123** [YvanYin/Metric3D#4]
The poses are from colmap, how do you align its scale to real world scale?
The depths are meters but poses from colmap are of arbitrary unit, there must be some sort of alignment.

**Comment by JUGGHM** [comment]
> > The poses are from colmap, how do you align its scale to real world scale? The depths are meters but poses from colmap are of arbitrary unit, there must be some sort of alignment.
> 
> Thank you for your interest! Actually we obtain initial poses with metric from RGB-D ORB-SLAM, and then refine them with colmap.
> 
> As there are a lot of details in this projects, many of them are not fully clarified in the paper.

Depth maps for RGB-D SLAM are given by our model

**Comment by kwea123** [comment]
thank you, will check the code once it's out

**Comment by yuancaimaiyi** [comment]
> The poses are from colmap, how do you align its scale to real world scale?这些姿势来自 colmap，如何将其比例与现实世界比例对齐？ The depths are meters but poses from colmap are of arbitrary unit, there must be some sort of alignment. 深度为米，但 colmap 的姿势是任意单位，必须有某种对齐。

葵大，可以使用我这个仓库：https://github.com/yuancaimaiyi/colmap-fusion-gps/tree/fusion-gps ，融合了先验位置信息，是有尺度的colmap
