### ISSUE TITLE
In-the-Wild Mode，The result is very different from the true value

### ISSUE THREAD

**Issue by Ghul-huan** [YvanYin/Metric3D#41]
<img width="552" alt="结果图" src="https://github.com/YvanYin/Metric3D/assets/32660191/d32c4f72-9506-4f1d-bedb-006eb87510a2">

**Comment by Ghul-huan** [comment]
crop_size = (544,960),the cam_in [487,487,479.8,266] ,img_size :[540,960],depth_scale =1 ,Autonomous driving scene

**Comment by JUGGHM** [comment]
> crop_size = (544,960),the cam_in [487,487,479.8,266] ,img_size :[540,960],depth_scale =1 ,Autonomous driving scene

Thank you for reaching out but I think your configuration is correct. 

Our suggestion is that you could probably use a scale align factor obtained by [rough median match](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/utils/do_test.py#L258C39-L258C45). You may apply this factor for your inference. According to our knowledge, the scale drifts from images by the same camera are quite close.

We are still focusing on this to shrink the scale gap between the zero-shot model and real-world application.
