### ISSUE TITLE
[Questions regarding focal length and input depth scale] 

### ISSUE THREAD

**Issue by idra79haza** [YvanYin/Metric3D#46]
Hi! thank you for the great work!!

I was just wondering if I have depth in mm unit, can I get the result of mm unit of ply? If so, what should I change? 

Is it right that I change convlarge.0.3_150.py's focal_length to 1.0?
![image](https://github.com/YvanYin/Metric3D/assets/37795618/4f5c9d08-74cc-4adf-9034-2cd60f513f00)

And also for the gene_annos_*.py file, should I change it's depth_scale into 1.?
![image](https://github.com/YvanYin/Metric3D/assets/37795618/8e24f08f-765b-42c6-b657-d924be3fcae3)

Thank you in advance!

**Comment by JUGGHM** [comment]
> Hi! thank you for the great work!!
> 
> I was just wondering if I have depth in mm unit, can I get the result of mm unit of ply? If so, what should I change?
> 
> Is it right that I change convlarge.0.3_150.py's focal_length to 1.0? ![image](https://private-user-images.githubusercontent.com/37795618/295146764-4f5c9d08-74cc-4adf-9034-2cd60f513f00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTY0NzQsIm5iZiI6MTcwNDc5NjE3NCwicGF0aCI6Ii8zNzc5NTYxOC8yOTUxNDY3NjQtNGY1YzlkMDgtNzRjYy00YWRmLTkwMzQtMmNkNjBmNTEzZjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOTk5Yjg4YjQzYzRjNmFjOTUxZTBiYzM0ZmE1ZmNhNmFjYmNkNWI4M2E3NDQ3Y2IzYjE4YjgxMTIxYWMyMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jKR2jE3mU9a6jvtTzBrMAcQCWEYvH7eu2QPclt42rGE)
> 
> And also for the gene_annos_*.py file, should I change it's depth_scale into 1.? ![image](https://private-user-images.githubusercontent.com/37795618/295146946-8e24f08f-765b-42c6-b657-d924be3fcae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTY0NzQsIm5iZiI6MTcwNDc5NjE3NCwicGF0aCI6Ii8zNzc5NTYxOC8yOTUxNDY5NDYtOGUyNGYwOGYtNzY1Yi00MmM2LWI2NTctZDkyNGJlM2ZjYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZTI0NzdkMjdlMTgwZTQ2ZDAzNDQwYjRhMzBlYWIzNzcyOTFjYWNkNGViMjlmZDMzNTRjMDhkODAyZGUxMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QIZTikkbQ4FuLrGlgSCslMv42TPc9nn-Z5sFMt3w8y8)
> 
> Thank you in advance!

Thank you for your interest! For depth evaluation, the depth_scale  should be 1000 then (1m / 1mm as you said). Do not change others.

If you want to get ply with mm unit, just multiply pcd by 1000 before [generating the file](https://github.com/YvanYin/Metric3D/blob/377e6c6642d0aca7aaa5a19e58fdcf5d0fd3d910/mono/utils/do_test.py#L314).
