### ISSUE TITLE
Another example on real data

### ISSUE THREAD

**Issue by kwea123** [YvanYin/Metric3D#5]
<img width="837" alt="截圖 2023-08-12 下午12 25 26" src="https://github.com/YvanYin/Metric3D/assets/11364490/88d51862-2ea4-42b8-9ff9-f25eb1bed83b">

![IMG_7002](https://github.com/YvanYin/Metric3D/assets/11364490/b55e364a-ea69-4b3c-b18e-5a599b2bf11c)

![IMG_7004](https://github.com/YvanYin/Metric3D/assets/11364490/4feda2d6-a6fa-4d49-863a-c3dde3183450)

So I compared the result v.s. real distance. (The focal is from iphone) It seems that there is still a large gap. The relative error is 33% and 36% in the two measurements.

Some examples in figure 7 also shows this big error, so I guess this is what to expect. This is not a bug, just some report.

**Comment by JUGGHM** [comment]
Thank you for your case! We hope more data and stronger models shall help us shrink metric errors in the future.
