### ISSUE TITLE
处理连续视频帧的深度一致性较差

### ISSUE THREAD

**Issue by Linkersem** [YvanYin/Metric3D#54]
你好，我在尝试处理连续视频帧的时候，遇到了输出深度值跳变的问题，比如某个点的深度值，我一直对着这个地方不动，但是这个点的深度值会从1.2左右跳变到3.5左右，会这样反复出现， 请问这个是什么原因导致的呀？

**Comment by YvanYin** [comment]
这个是因为模型自身的不确定性导致的。模型没有针对video做smoothness，因此会有这个问题。
