### ISSUE TITLE
About metrics reported on NYU and KITTI in Tab.1 and Tab. 4

### ISSUE THREAD

**Issue by songlin** [YvanYin/Metric3D#57]
Hi,

Thanks for sharing the great work! 

I have questions regarding the metrics reported on NYU and KITTI in Tab. 1 and Tab. 4.

1. From Tab. 1, the $\delta_1$ on NYU are **0.925** and  0.944 for CSTM_image and CSTM_label respectively.
2. From Tab. 4, the $\delta_1$ on NYU are **0.963** and  0.966 for CSTM_image and CSTM_label respectively.

What causes the differences here?  Is it the different backbone used or just the affine-invariant alignment used only in Tab.4 but not Tab. 1?

![tab 1](https://github.com/YvanYin/Metric3D/assets/853045/8ebdf40c-42ce-48f1-9f0d-923c0c95b4c6)
![tab 4](https://github.com/YvanYin/Metric3D/assets/853045/bff1fa44-8e17-41c9-9392-fb6edf6720d2)

**Comment by JUGGHM** [comment]
Thank you for your interest! In tab1. it is metric depth comparison by comparing prediction and GT directly. In tab2. it is relative/affine invariant depth compared, where the median of prediction and GT label is aligned by linear transformation. We will clarify it in our upcoming paper.
