### ISSUE TITLE
How can we test our own images?

### ISSUE THREAD

**Issue by linjing7** [YvanYin/Metric3D#6]
Hi, thanks for your excellent work. I'm wondering how can we test the metric depth of our own images. Besides, if I have an in-the-wild image, how can I test the size of the objects in it? For example, how do you get the size of the table in Figure 1?

**Comment by YvanYin** [comment]
Hi, you can follow the following steps.
1. Obtain the focal length of the corresponding camera. You can read the metadata and find out which camera takes this image. And then google the camera to get the sensor size and resolution.  `focal = sensor_size_width / resolution_width`. Note this is a very coarse calculation. It will affect the metrology accuracy. But currently, I do not have other tools to get a more accurate focal length from a single in-the-wild image. 
2. Feed the focal length and image to the network to get the metric depth.
3. Reconstruct the point cloud with the predicted depth and the focal length.
4. Use some tools, such as Meshlab, to measure the table's size.

**Comment by linjing7** [comment]
Okay, thanks for your detailed reply! I found that there exists severe noise at the edge of the point cloud, i.e., the depth of the object edge is very noisy. Do you have any idea to solve this problem?

**Comment by YvanYin** [comment]
Maybe you can try the following methods.
1. Use our provided confidence map to remove edges' depths.
2. Use a point cloud filter to filter edges' sparse points. e.g. use open3d:` remove_radius_outlier` this function. There are many other point cloud filters. You can refer to open3d documents. 
3. Maybe the image's guided filter can also help you to reduce edges' noises.

**Comment by linjing7** [comment]
Okay, thank you very much! I will have a try.
