### ISSUE TITLE
训练代码？ 

### ISSUE THREAD

**Issue by huster-wugj** [YvanYin/Metric3D#60]
你好，非常好的工作。
请问有计划发布训练代码吗？

**Comment by JUGGHM** [comment]
有的，很快会有

**Comment by huster-wugj** [comment]
> 有的，很快会有

感谢！ 
同时Driod-slam部分也会开放出来吗？

**Comment by YvanYin** [comment]
training codes are released.

**Comment by JUGGHM** [comment]
> > 有的，很快会有
> 
> 感谢！ 同时Driod-slam部分也会开放出来吗？

会，但是得过一段时间
