### ISSUE TITLE
请教关于crop size的问题

### ISSUE THREAD

**Issue by mayunchao1994** [YvanYin/Metric3D#63]
这是一个非常出色且实用的工作！

想请教关于输入图像大小的问题：
看到代码中，在推理时，先将输入图片的焦距变换到canonical_focal得到cano_label_scale_ratio。再将图片resize后crop到指定的crop size，在这个过程中根据图像尺寸变化得到resize_label_scale_ratio。我在测试时发现，比如crop size分别是[784, 784]和[392, 392]，模型的输出“pred_depth, confidence, output_dict = model.module.inference(data)”，pred_depth的数值前者是后者的两倍多，但pred_depth = pred_depth * normalize_scale / scale_info，其中scale_info后者是前者的两倍，这就导致同样的模型输入不同的crop size得到的深度图数值整体相差几倍。我理解crop size的不同最后会通过resize_label_scale_ratio反应到depth上，应该是没有影响的。

请问推理时crop size是需要和训练时保持一致吗？如果需要一致，vit.raft5.large的crop size应该是多少呢

**Comment by mayunchao1994** [comment]
补充一下：对于模型的输入如果分别是[784, 784]和[392, 392]，得到的深度数值(大概可以看全图的均值)前者应该是后者的两倍吗？我理解应因为图像尺寸是两倍的关系对应的焦距也应该是两倍。resize_for_input函数中：
resize_ratio_h = output_shape[0] / canonical_shape[0]
resize_ratio_w = output_shape[1] / canonical_shape[1]
to_scale_ratio = min(resize_ratio_h, resize_ratio_w)
看到传入的canonical_shape是rgb原始尺寸，这样最后label_scale_factor=1/to_scale_ratio是不是应该是：label_scale_factor=to_scale_ratio呢？因为最后pred是除以scale_info。
我尝试这样修改后，输入不同的crop size得到的深度数值确实接近了，但数值明显比真实深度值大了好几倍。

**Comment by JUGGHM** [comment]
> 补充一下：对于模型的输入如果分别是[784, 784]和[392, 392]，得到的深度数值(大概可以看全图的均值)前者应该是后者的两倍吗？我理解应因为图像尺寸是两倍的关系对应的焦距也应该是两倍。resize_for_input函数中： resize_ratio_h = output_shape[0] / canonical_shape[0] resize_ratio_w = output_shape[1] / canonical_shape[1] to_scale_ratio = min(resize_ratio_h, resize_ratio_w) 看到传入的canonical_shape是rgb原始尺寸，这样最后label_scale_factor=1/to_scale_ratio是不是应该是：label_scale_factor=to_scale_ratio呢？因为最后pred是除以scale_info。 我尝试这样修改后，输入不同的crop size得到的深度数值确实接近了，但数值明显比真实深度值大了好几倍。

你可能没有调整焦距，我在新的问题里回复你了
