### ISSUE TITLE
请教resize和焦距的问题

### ISSUE THREAD

**Issue by mayunchao1994** [YvanYin/Metric3D#64]
这是一个非常实用的工作，把焦距的差异通过映射label而不是融入网络学习的思想非常赞，大道至简！
在inference时，由于输入到网络的size和图像原size不同，需要做resize，代码中同时计算了to_scale_ratio，我理解是因为图像尺寸变了相当于焦距也变了，需要同时计算scale的变化。这里有个疑问：
我理解网络学习深度的线索是学习到物体在整张图片的面积占比而不是物体的绝对面积大小，以这个线索为前提的话，同一个网络，输入1x和2x图像，网络得到的输出除了因为计算量的差异带来镂空等细节不同外，深度值应该是相同的。我测试DepthAnything的kitti模型，用不同分辨率输入，得到的深度值基本相同（比如min、max、mean这些度量以及对比每个像素点），但我测试Metric3D时发现不同尺寸输入的图像得到深度值有很大差异，请问这是由于在网络训练时，不同resize对应的label也做了scale变化导致的吗？

**Comment by mayunchao1994** [comment]
感谢回复！
我做resize同时调整了焦距。看到源码的过程是：比如我输入图像分辨率是1080*1440，焦距是1500，先将焦距映射到公共特征空间焦距1000，计算了cano_label_scale_ratio，然后在resize_for_input中，resize到540*720，计算出to_scale_ratio，这个to_scale_ratio我理解已经包含了焦距的变化，最后pred的scale = cano_label_scale_ratio/to_scale_ratio。其中计算to_scale_ratio时，还需要改乘焦距的变化吗？“仅仅调整了图像大小却没有调整焦距”，这里的调整焦距指在哪里调整呢

**Comment by JUGGHM** [comment]
> 感谢回复！ 我做resize同时调整了焦距。看到源码的过程是：比如我输入图像分辨率是1080_1440，焦距是1500，先将焦距映射到公共特征空间焦距1000，计算了cano_label_scale_ratio，然后在resize_for_input中，resize到540_720，计算出to_scale_ratio，这个to_scale_ratio我理解已经包含了焦距的变化，最后pred的scale = cano_label_scale_ratio/to_scale_ratio。其中计算to_scale_ratio时，还需要改乘焦距的变化吗？“仅仅调整了图像大小却没有调整焦距”，这里的调整焦距指在哪里调整呢

这个是作为用户在外部进行调整。（1） 作为用户，你不需要关注 "cano_label_scale_ratio", "to_scale_ratio"这些内容。（2）如果是同行需要了解其中原理，那么 你可以理解为： "仅仅调整了图像大小却没有调整焦距" 中“ 调整” 的原理 和 to_scale_ratio 一样，但同样，你不要调整两个变量中的另一个，在外部调整即可。

必须调整焦距的原因如下：
![image](https://github.com/YvanYin/Metric3D/assets/35299633/30281615-0996-49fc-aecc-f0bdec219184)
