### ISSUE TITLE
请教关于如何用自己的照片来输出三维点云的问题

### ISSUE THREAD

**Issue by aotemanxiaoy** [YvanYin/Metric3D#66]
非常令人敬佩的工作！非常感谢！
我在运行项目时碰到个问题：当我用野外模式并输入自己的照片时，得到的点云非常变形和失真。我看到，在readme中作者有解释：
Q1: Why depth maps look good but pointclouds are distorted?
Because the focal length is not properly set! Please find a proper focal length by modifying codes [here](https://github.com/YvanYin/Metric3D/blob/main/mono/utils/do_test.py#309) yourself.
请教一下，我具体需要在do_test.py中如何调整？
我比较疑惑的是#309行指向的是注释行：#309 pcd = reconstruct_pcd(pred_depth, intrinsic[0], intrinsic[1], intrinsic[2], intrinsic[3])
我是需要取消注释还是要在其他地方进行修改？谢谢！

**Comment by JUGGHM** [comment]
感谢关注！你可以把这一行 https://github.com/YvanYin/Metric3D/blob/eea9a486ac25472e8f06efb805bb780c0eaef6d4/mono/utils/do_test.py#L316 注释去掉，并把下面一行注释掉。这一行里面提供了更多可选内参，你也可以自行进行修改。但是生成多个点云速度很慢，所以被我注释掉了。
