### ISSUE TITLE
Visualization code for the pcd video

### ISSUE THREAD

**Issue by yuliangguo** [YvanYin/Metric3D#69]
Dear authors,

I found the video demos made out of the generated pcd files are amazing. Is that possible to release the code for generating those videos?

**Comment by JUGGHM** [comment]
> Dear authors,
> 
> I found the video demos made out of the generated pcd files are amazing. Is that possible to release the code for generating those videos?

In a close recent we cannot release the code because all the codes released are by our re-implementation in public environments. The overall pipeline is: (1) Generate all pointclouds for each frame in the video, (2) Find a good viewpoint and render the pointcloud video by open3d.

**Comment by apurvmmmec** [comment]
Dear authors,

When you calculate the metric depth for all frames in a video, how do you ensure the consistency in the depth values for the pixels that are visible in multiple frames. Without consistency in depth, wont there be abnormalities in the point cloud constructed using depths from these frames.

Thanks
