### ISSUE TITLE
About color of normal map

### ISSUE THREAD

**Issue by ActonLee** [YvanYin/Metric3D#70]
Hi, I want to know why the color of normal map is not like this:
![image](https://github.com/YvanYin/Metric3D/assets/88582462/91c53da5-4958-4dbc-982f-3c89c728e3d7)
Specifically, what's the 3-channel-order of the predicted normal map??

**Comment by YvanYin** [comment]
the order is nx, ny, nz.

**Comment by JUGGHM** [comment]
> Hi, I want to know why the color of normal map is not like this: ![image](https://private-user-images.githubusercontent.com/88582462/321795386-91c53da5-4958-4dbc-982f-3c89c728e3d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzU3MTMsIm5iZiI6MTcxMzg3NTQxMywicGF0aCI6Ii84ODU4MjQ2Mi8zMjE3OTUzODYtOTFjNTNkYTUtNDk1OC00ZGJjLTk4MmYtM2M4OWM3MjhlM2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMzAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNDc2OGUyN2ZjOGYxYmRkNDQ2OGRiZTRhNDllYjU1MzIyYTU3ZWRiNmEzYTQ5OTIyNDU5NjYxOWNmZDZjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GH0OP9JK2Joc26nMx9TBiJdO-SAWGyfSHcOOV32CoiM) Specifically, what's the 3-channel-order of the predicted normal map??

It is the same, use 255-{your map}
