### ISSUE TITLE
Call For HuggingFace Demo

### ISSUE THREAD

**Issue by isJHan** [YvanYin/Metric3D#71]
Hello, it's a wonderful job. I can't wait to dive into it. Unfortunately, there has no a quick way to try it.

So, can you upload this work to huggingface, and  provide a huggingface demo link. I believe it's also a better way to promote your great work!

Thanks!

**Comment by YvanYin** [comment]
Hi, we have a simple HG demo, see https://huggingface.co/spaces/JUGGHM/Metric3D.
