### ISSUE TITLE
ConvNeXt-Tiny模型

### ISSUE THREAD

**Issue by Minnchong** [YvanYin/Metric3D#72]
您好，请问ConvNeXt-Tiny模型参数量是多少？大概什么时候发布？ @JUGGHM

**Comment by JUGGHM** [comment]
一周左右？这个模型看上去很小，但在a100上跑起来跟large差不多，而且只在室外数据集上训过，泛化性一般

**Comment by Minnchong** [comment]
@JUGGHM 好的，感谢您的回复

**Comment by Minnchong** [comment]
@JUGGHM @YvanYin 
Is there any plan to release a tiny model recently?

**Comment by cverrier** [comment]
> @JUGGHM @YvanYin Is there any plan to release a tiny model recently?

@Minnchong It seems that there is a small transformer that has been available recently, but not sure if this is what you are looking for:
https://github.com/YvanYin/Metric3D/blob/2118ec93a24f0f80204f56be96459ac049d37bf4/README.md?plain=1#L293

**Comment by Minnchong** [comment]
@cverrier Thank you for your reminder ：-）
