### ISSUE TITLE
mmcv的具体版本

### ISSUE THREAD

**Issue by JiBingdong** [YvanYin/Metric3D#73]
作者您好：
当我执行pip install -r requirements_v2.txt时发现pytorch2.0.1与mmcv出现冲突，无法安装mmcv，应该是由于mmcv版本更新导致的不兼容，因此希望作者能够给出mmcv的具体版本。

**Comment by stan1512** [comment]
mmcv | 2.1.0 | 2.1.0
torch | 2.2.2 | 2.2.2
torchvision | 0.17.2 | 0.17.2
These are the versions I am using

**Comment by YvanYin** [comment]
@stan1512  thx for answering.

**Comment by JiBingdong** [comment]
Thanks，i try to install torch2.0.1 and mmcv1.7.2，also worked.
