### ISSUE TITLE
Training Cost

### ISSUE THREAD

**Issue by stan1512** [YvanYin/Metric3D#74]
May I ask what kind of GPU is needed for training private data？

**Comment by JUGGHM** [comment]
> May I ask what kind of GPU is needed for training private data？

It is A100 GPU. To train a small/large/giant model you need 32/48/64 GPUs. To finetune it on small datasets, you will need "only" 8 GPUs

**Comment by luuude** [comment]
64 a100 gpus? Wow, for how long did you train it? Sounds expensive!

**Comment by JUGGHM** [comment]
> 64 a100 gpus? Wow, for how long did you train it? Sounds expensive!

About three weeks for 800k steps if not interrupted (Impossible).
