### ISSUE TITLE
Config File for DINO2reg-ViT-giant2

### ISSUE THREAD

**Issue by VenkatSBitra** [YvanYin/Metric3D#75]
Can you please provide the config file for the DINO2reg-ViT-giant2. Currently there are config files only for: DINO2reg-ViT-Large and DINO2reg-ViT-Small.

**Comment by JUGGHM** [comment]
> Can you please provide the config file for the DINO2reg-ViT-giant2. Currently there are config files only for: DINO2reg-ViT-Large and DINO2reg-ViT-Small.

Updated now and please try it.

**Comment by VenkatSBitra** [comment]
I am getting the following error:

Failed to find function: mono.model.backbones.vit_giant2_reg

when running: torch.nn.DataParallel(get_configured_monodepth_model(cfg, ))

**Comment by JUGGHM** [comment]
> I am getting the following error:
> 
> Failed to find function: mono.model.backbones.vit_giant2_reg
> 
> when running: torch.nn.DataParallel(get_configured_monodepth_model(cfg, ))

That's my mistake, I have added the model definitions now.

**Comment by runningneverstop** [comment]
![image](https://github.com/YvanYin/Metric3D/assets/86957090/1f4abfbf-4c8d-40c8-b912-af74288c9ab1)
