### ISSUE TITLE
RGB channels misinterpreted

### ISSUE THREAD

**Issue by haojiang95** [YvanYin/Metric3D#77]
Hello, thanks for the great work! I noticed something looks like a bug about misinterpreted RGB channels

This piece of code assumes the image in "BGR" format before the conversion 
https://github.com/YvanYin/Metric3D/blob/b83e18a53b69958f3bc5d36d2eb3613432198b27/mono/utils/do_test.py#L189-L190

However, the image is loaded in "RGB" format because of the `[:, :, ::-1]`
https://github.com/YvanYin/Metric3D/blob/b83e18a53b69958f3bc5d36d2eb3613432198b27/mono/utils/do_test.py#L247

**Comment by JUGGHM** [comment]
Thank you for your notification! This is very strange because I think we fixed it several months ago... Anyway, it is fixed now.
