### ISSUE TITLE
leveraging stereo data in training

### ISSUE THREAD

**Issue by iariav** [YvanYin/Metric3D#79]
Hi, 
I have a dataset containing pairs of stereo images, with GT depth data that corresponds to one of the images (left).
is there some way to utilize the fact that I have pairs of images instead of only a single image to improve training\results?

would appreciate any suggestions.
thanks

**Comment by JUGGHM** [comment]
> Hi, I have a dataset containing pairs of stereo images, with GT depth data that corresponds to one of the images (left). is there some way to utilize the fact that I have pairs of images instead of only a single image to improve training\results?
> 
> would appreciate any suggestions. thanks

Thank you for your interest! It depends on your setup. 

(1) For indoor scenarios let's suppose the GT maps are dense (from RGB-D cameras), then you could consider to construct GT depth map for right-camera images by projection and bilinear upsampling. These data-pairs can enlarge your dataset capacity.

(2) For outdoor scenarios you might have obtained the groundtruth by LiDAR. Then individually I recommend to generate a pseudo GT depth maps from in-the-wild stereo matching models (classical methods like RaftStereo, or SoTA methods like CREStereo/NerfStereo). Such pseudo labels are dense but might not so accurate as LiDAR measurements. Therefore you could supervise the training by both Real GT labels and psuedo GT labels, where loss using the latter one could be multiplied by a small-value weighted loss.

Besides, you can use left-right photometric consistency losses to improve the weakly supervised regions. (like those without GT labels)

**Comment by iariav** [comment]
Thank you for the elaborated response!
My dataset is indeed outdoor and the gt measurements do come from LIDAR. I will try what you suggested. 
regarding the left-right consistency loses - that sounds like a very interesting direction! Do you happen to know of any good implementations of such losses that could be easily incorporated to your pipeline?

**Comment by JUGGHM** [comment]
> Thank you for the elaborated response! My dataset is indeed outdoor and the gt measurements do come from LIDAR. I will try what you suggested. regarding the left-right consistency loses - that sounds like a very interesting direction! Do you happen to know of any good implementations of such losses that could be easily incorporated to your pipeline?

I think this has been widely studied before, you can refer to early works for self-supervised mono-depth like [Unsupervised Monocular Depth Estimation with Left-Right Consistency](https://arxiv.org/abs/1609.03677)].

**Comment by JUGGHM** [comment]
> thanks. but for that I must have accurate intrinsics of the cameras used to record the data, right?

In the framework of metric3d, this is true.
