### ISSUE TITLE
How to combine with Droid-slam?

### ISSUE THREAD

**Issue by liyupeng-ing** [YvanYin/Metric3D#8]
Hi, thanks for contributing such great work! I was wondering how you combined monocular depth with Droid-slam? Is the monocular depth used for Droid-slam initialization? Or is it just taking the pose provided by Droid-slam and fusing it with TSDF?

**Comment by JUGGHM** [comment]
> Hi, thanks for contributing such great work! I was wondering how you combined monocular depth with Droid-slam? Is the monocular depth used for Droid-slam initialization? Or is it just taking the pose provided by Droid-slam and fusing it with TSDF?

Thanks for your interest!  We use the predicted metric depth as a prior for the RGBD mode of droid SLAM. The depth serves as initial clues and regularization items. No fusing stage is needed.

**Comment by Vincent630** [comment]
> > 嗨，感谢您贡献如此出色的工作！我想知道你是如何将单筒望远镜深度与 Droid-slam 结合起来的？单眼深度是否用于 Droid-slam 初始化？或者它只是采用 Droid-slam 提供的姿势并将其与 TSDF 融合？
> 
> 感谢您的关注！我们使用预测的度量深度作为 droid SLAM 的 RGBD 模式的先验。深度用作初始线索和正则化项。不需要熔融阶段。

i wonder how to get the metric depth ?because i find out that output result is not like metric depth(near region big value，far region small value)
