### ISSUE TITLE
Speed Up Inference

### ISSUE THREAD

**Issue by mees** [YvanYin/Metric3D#83]
Hi there,
is there any way to speed up inference by increasing the batch size for larger datasets?

**Comment by YvanYin** [comment]
Hi, we will add this feature soon.

**Comment by ZachL1** [comment]
We just added support for batch inference. See the parameter `batch_size` in `mono/tools/test_scale_cano.py`.

We have only implemented batch data parallelization for model inference, but not for other pre/post processing due to possible different sized images within the same batch. Hope it helps.

**Comment by bhack** [comment]
Is there a way to use the batch in the torchub/torchload example?

**Comment by ZachL1** [comment]
Sure. The torchhub model only supports batch inference. I use batchsize=1 in the example:
https://github.com/YvanYin/Metric3D/blob/fd90d0dad05d913c4f45ed7a9789b8f1dfde22e0/hubconf.py#L179
