### ISSUE TITLE
normals not normal

### ISSUE THREAD

**Issue by yotofu** [YvanYin/Metric3D#86]
I visualize the normal after i predict the depth and normal use code blow
![image](https://github.com/YvanYin/Metric3D/assets/24996527/ab5c8e63-8c78-4c87-8a2b-28ee61cf36bf)
the depth is normal:
![image](https://github.com/YvanYin/Metric3D/assets/24996527/d5ed5e1b-7648-47de-8aa0-88d331db5290)
but the normals not good:
![image](https://github.com/YvanYin/Metric3D/assets/24996527/673e0ae4-b989-4121-9b80-c1b8a838676d)

**Comment by YvanYin** [comment]
could you please provide the original image?

**Comment by yotofu** [comment]
it's caused by the error of unpadding the pred normal in my code.  It's normal now after i fix this part.

**Comment by sonnefred** [comment]
> it's caused by the error of unpadding the pred normal in my code. It's normal now after i fix this part.

Hi, how do you visualize normals and save it? Could you share your script a bit? Thanks!
