### ISSUE TITLE
Unable to adjust scale of depth correctly in the wild-mode 

### ISSUE THREAD

**Issue by utsavrai** [YvanYin/Metric3D#87]
So far as per the suggestions in issue #78, I have provided the intrinsic values of the camera. Since the test images have no ground truth depth, I am trying to adjust the scale of depth to obtain an approximate metric depth. Also as these images are taken from a close range camera for robotic surgical purpose, the scale has to be set in mm. I want to understand how to adjust the scale of output depth effectively since I know the dimension of an object in the RGB image, I want to use it as reference to set the scale appropriately. 

<img src="https://github.com/YvanYin/Metric3D/assets/25121619/b6dc89b4-2e7e-4211-ba63-b36f1166040e" width="200" height="400">
<img src="https://github.com/YvanYin/Metric3D/assets/25121619/d661e634-59a4-4afb-8e06-fe875f470a3c" width="200" height="400">

As mentioned above I have adjust the intrinsic value in `/mono/utils/custom_data.py` as

```
def load_data(path: str):
    rgbs = glob.glob(path + '/*.jpg') + glob.glob(path + '/*.png')
    intrinsic =  [818.0454, 815.9985, 476.3116, 298.1767] #[721.53769, 721.53769, 609.5593, 172.854]
    data = [{'rgb': i, 'depth': None, 'intrinsic': intrinsic, 'filename': os.path.basename(i), 'folder': i.split('/')[-3]} for i in rgbs]
    return data
```

Currently I am using `metric_depth_vit_giant2_800k.pth` and would like to know what adjust can be made to approximate the depth scale since I have the cad model of the head of the surgical tool as shown below

<img src="https://github.com/YvanYin/Metric3D/assets/25121619/f3fc59fd-73dc-4e54-b08c-3880de288eb0" width="400" height="200">

**Comment by YvanYin** [comment]
Hi, our model may not predict the depth in mm metric. We did not enclose any samples as your close images. I have some suggestions but they may not work. You can use our model to predict depth and use some reference objects in our image to rectify the metric. i.e. you know some structures' real size in our photo, measure the size in our depths, and then scale the predicted depth. 
Another suggestion: in the above colored depth map, owing to some extremely large values in prediction, the depth is normalized to very small values.   You can clip the prediction to obtain better visual results.
