### ISSUE TITLE
How is the camera model (4-channel map) used during model inference?

### ISSUE THREAD

**Issue by qqsh0214** [YvanYin/Metric3D#9]
Thanks for contributing such a good job! When I studied the test code (do_test.py), I found that you have converted the camera intrinsic parameters into a 4-channel map (principle point location and FoV map) as the camera model. The camera model is further passed into the model inference part. 

However, when I checked the decoder code (HourGlassDecoder.py), I found that the camera model does not seem to be used, so I would like to ask where the camera model is used during model inference? Is it possible to perform model inference as described in the paper using only camera intrinsic parameters without generating a camera model?

Looking forward to your reply and tips!

**Comment by JUGGHM** [comment]
Thank you for your interest! The predicted depth is scaled [here](https://github.com/YvanYin/Metric3D/blob/3fca9c149e5dcd176f736c8632306450f8cd8ead/mono/utils/do_test.py#L166).

**Comment by qqsh0214** [comment]
> Thank you for your interest! The predicted depth is scaled [here](https://github.com/YvanYin/Metric3D/blob/3fca9c149e5dcd176f736c8632306450f8cd8ead/mono/utils/do_test.py#L166).

Thanks for you reply! The predicted depth is scaled **only** using 'normalize_scale' and 'scale_info', but the 'cam_model' with 4-channel map does not seem to be used. Do I understand correctly?

**Comment by JUGGHM** [comment]
> > Thank you for your interest! The predicted depth is scaled [here](https://github.com/YvanYin/Metric3D/blob/3fca9c149e5dcd176f736c8632306450f8cd8ead/mono/utils/do_test.py#L166).
> 
> Thanks for you reply! The predicted depth is scaled **only** using 'normalize_scale' and 'scale_info', but the 'cam_model' with 4-channel map does not seem to be used. Do I understand correctly?

The scale is adjusted [here](https://github.com/YvanYin/Metric3D/blob/3fca9c149e5dcd176f736c8632306450f8cd8ead/mono/utils/do_test.py#L195C18-L195C18), where intrinsic (focal length) is used

**Comment by qqsh0214** [comment]
Thanks for your reply!
