### ISSUE TITLE
Question regarding losses

### ISSUE THREAD

**Issue by choillee82** [YvanYin/Metric3D#94]
Thank you for sharing great work!

I have a question regarding losses in your experiment.
In your paper, only 4 losses(PWN_Planes, SiLog, VNL, HDSML_random) are used for the model, even though many losses are implemented in codes. 
Are these losses best choose to make better depth performance with many trials?
If you don't mind could you let me know why you select these losses in your experiment?

**Comment by YvanYin** [comment]
We implement many losses and find that [PWN_Planes, SiLog, VNL, HDSML_random] has the best performance. You can try them by yourself. We didn't study deep in this part.
