### ISSUE TITLE
Depth scale vs Metric scale

### ISSUE THREAD

**Issue by Sparsh913** [YvanYin/Metric3D#95]
Hi Authors,
Awesome work!

How do these two scales differ? What functions do they serve? While json creation, parameter 'depth scale' has been used. But in training/mono/configs/_base_/datasets folder, the respective .py files use 'metric scale'. I'd really appreciate a clarification.

Thanks!

**Comment by YvanYin** [comment]
'metric scale' in 'training/mono/configs/base/datasets':  it is used to recover real metric. For example, kitti dataset save the depth map in a 16-bit png file and they scale the real depth with 256 to perserve the numerical precision. Thus in our json, we create this 'metric scale' to scale the loaded depth file to recover the metric.

**Comment by Sparsh913** [comment]
Thanks a lot for your response!
So I'm particularly asking if the 2 parameters, 'depth scale' and 'metric scale' are exactly the same since both have been used to recover the real depth?

**Comment by YvanYin** [comment]
Could you point out which 'depth scale'?

**Comment by Sparsh913** [comment]
I'm referring to the "depth scale" parameter used in files, data/gene_annos_kitti_demo.py and data/gene_annos_nyu_demo.py

**Comment by YvanYin** [comment]
It is same as 'metric scale'. 
https://github.com/YvanYin/Metric3D/blob/main/data/gene_annos_nyu_demo.py: original nyu data depth has been scaled 1000 to save in a PNG file.

**Comment by Sparsh913** [comment]
Thank you!
To understand it better, can you also explain why 200 has been chosen as the metric scale for DDAD dataset? I understand that your pipeline expects the DDAD training depth to be in 16bit format. But DDAD has GT depth ranging from 0 to 250 m (as per their official documentation: https://github.com/TRI-ML/DDAD?tab=readme-ov-file#dataset-details). With 200 as metric scale I don't understand how you'd recover the original metric depth range from a 16bit format (65500/200 = 327.5).

**Comment by YvanYin** [comment]
When we process DDAD dataset, we transform sparse lidar to a depth map and scale the depth with 200. Thus for DDAD, the metric scale is 200.

**Comment by Sparsh913** [comment]
Understood, thanks a lot!
