### ISSUE TITLE
generate only a depth matrix without generating a 3D point cloud

### ISSUE THREAD

**Issue by Thundermean-sky** [YvanYin/Metric3D#97]
Hello, thanks for sharing, great work!

In my experiment, I only need to use the depth matrix, not the point cloud, but I don't seem to see this function. However, the huggingface website you provided does have this, so I would like to ask, is it possible to generate only the depth matrix at the code level?

**Comment by YvanYin** [comment]
See https://github.com/YvanYin/Metric3D/blob/main/mono/utils/do_test.py#L254.  It outputs the predicted depth.

**Comment by Thundermean-sky** [comment]
> See https://github.com/YvanYin/Metric3D/blob/main/mono/utils/do_test.py#L254. It outputs the predicted depth.

thanks!
