### ISSUE TITLE
Camera parameters of taskonomy

### ISSUE THREAD

**Issue by choillee82** [YvanYin/Metric3D#99]
Thank you for sharing the great work!

I tried to train your model with taskonomy dataset, but there was no information regarding camera parameter in dataset scripts. 
In your case, how to get the camera parameters of taskonomy dataset you used for training?
If you don't mind could you let me know how to get the camera parameter of taskonomy dataset?

**Comment by YvanYin** [comment]
Please read this https://github.com/StanfordVL/taskonomy/tree/master/data. They provide Field of View, which can be transferred to the focal length.

**Comment by choillee82** [comment]
Which kind of focal length do you use in your experiment? Pixel represented focal length or real world scale focal length(mm)?
Datasets you used to train model, they seems support different of focal length depend on datasets.
For example, taskonomy dataset only provide fov information, so to convert it to camera parameter, focal length should be pixel represented value.
But, As far as i know, Nyuv2 and kitti they provide focal length in real world scale(mm).

My question is 
1. Which kind of focal length do you use to align data(canonical transform) with same focal space? pixel or real ?
2. How to convert real to pixel or pixel to real?
